/**
 * AltaProfesor2.java
 * Version 1
 * 31/01/2016
 * Copyright (c) Wiscorp Mexicali,BC
 * All rights reserved
 */

package Vista;

import Controlador.CVistaProfesor;
import Interfaces.ICierraVentana;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import Interfaces.IAltaProfesor;

/**
 * Clase que contiene la interfaz gráfica del registro de los profesores
 * @author David Omar Cabrera Bernal
 */
public class VAltaProfesor extends javax.swing.JFrame implements IAltaProfesor{
    
    CVistaProfesor control;  //Variable que lleva el control de la GUI
    int fila = -1; //Variable que lleva el control de la fila de las danzas ingresadas
    
    /**
     * Creates new form AltaProfesores
     */
    public VAltaProfesor() throws SQLException, Exception {
        //Se inician los valores de la interfaz grafica y se crea el objeto
        //que llevara el control de las acciones de la GUI
        initComponents();
        txNumProfesor.setEditable( false );
        control = new CVistaProfesor( this );
        //Se obtiene el numero del profesor que tendra al ser registrado
        control.obtenerNumeroProfesor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CancelarButton = new javax.swing.JPanel();
        btCancelar = new javax.swing.JButton();
        btAceptar = new javax.swing.JButton();
        jpNombreCompleto = new javax.swing.JPanel();
        etNombre = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        txApellidoPaterno = new javax.swing.JTextField();
        etApellidoPaterno = new javax.swing.JLabel();
        etApellidoMaterno = new javax.swing.JLabel();
        txApellidoMaterno = new javax.swing.JTextField();
        etNumProfesor = new javax.swing.JLabel();
        txNumProfesor = new javax.swing.JTextField();
        jpContacto = new javax.swing.JPanel();
        etTelefonoCasa = new javax.swing.JLabel();
        txTelCasa = new javax.swing.JTextField();
        etTelefonoCelular = new javax.swing.JLabel();
        txTelCel = new javax.swing.JTextField();
        etCorreo = new javax.swing.JLabel();
        txCorreo = new javax.swing.JTextField();
        etFacebook = new javax.swing.JLabel();
        txFacebook = new javax.swing.JTextField();
        jpDanzas = new javax.swing.JPanel();
        spDanzas = new javax.swing.JScrollPane();
        tbDanzas = new javax.swing.JTable();
        txDanza = new javax.swing.JTextField();
        etDanza = new javax.swing.JLabel();
        btAgregar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de profesor");
        setMaximumSize(new java.awt.Dimension(662, 425));
        setMinimumSize(new java.awt.Dimension(662, 425));
        setPreferredSize(new java.awt.Dimension(662, 425));

        CancelarButton.setLayout(null);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        CancelarButton.add(btCancelar);
        btCancelar.setBounds(230, 360, 90, 30);

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        CancelarButton.add(btAceptar);
        btAceptar.setBounds(330, 360, 90, 30);

        jpNombreCompleto.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre completo"));
        jpNombreCompleto.setLayout(null);

        etNombre.setText("Nombre");
        jpNombreCompleto.add(etNombre);
        etNombre.setBounds(170, 20, 50, 14);

        txNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNombreActionPerformed(evt);
            }
        });
        jpNombreCompleto.add(txNombre);
        txNombre.setBounds(170, 40, 130, 25);

        txApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txApellidoPaternoActionPerformed(evt);
            }
        });
        jpNombreCompleto.add(txApellidoPaterno);
        txApellidoPaterno.setBounds(330, 40, 140, 25);

        etApellidoPaterno.setText("Apellido Paterno");
        jpNombreCompleto.add(etApellidoPaterno);
        etApellidoPaterno.setBounds(330, 20, 90, 14);

        etApellidoMaterno.setText("Apellido materno");
        jpNombreCompleto.add(etApellidoMaterno);
        etApellidoMaterno.setBounds(490, 20, 100, 14);

        txApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txApellidoMaternoActionPerformed(evt);
            }
        });
        jpNombreCompleto.add(txApellidoMaterno);
        txApellidoMaterno.setBounds(490, 40, 130, 25);

        etNumProfesor.setText("Número de profesor");
        jpNombreCompleto.add(etNumProfesor);
        etNumProfesor.setBounds(10, 20, 120, 14);
        jpNombreCompleto.add(txNumProfesor);
        txNumProfesor.setBounds(10, 40, 130, 25);

        CancelarButton.add(jpNombreCompleto);
        jpNombreCompleto.setBounds(10, 10, 640, 80);

        jpContacto.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));
        jpContacto.setLayout(null);

        etTelefonoCasa.setText("Teléfono de casa");
        jpContacto.add(etTelefonoCasa);
        etTelefonoCasa.setBounds(10, 20, 110, 14);

        txTelCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelCasaActionPerformed(evt);
            }
        });
        jpContacto.add(txTelCasa);
        txTelCasa.setBounds(10, 40, 130, 25);

        etTelefonoCelular.setText("Teléfono Celular");
        jpContacto.add(etTelefonoCelular);
        etTelefonoCelular.setBounds(170, 20, 100, 14);

        txTelCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelCelActionPerformed(evt);
            }
        });
        jpContacto.add(txTelCel);
        txTelCel.setBounds(170, 40, 130, 25);

        etCorreo.setText("Correo electrónico");
        jpContacto.add(etCorreo);
        etCorreo.setBounds(330, 20, 110, 14);

        txCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCorreoActionPerformed(evt);
            }
        });
        jpContacto.add(txCorreo);
        txCorreo.setBounds(330, 40, 140, 25);

        etFacebook.setText("Cuenta de Facebook");
        jpContacto.add(etFacebook);
        etFacebook.setBounds(490, 20, 120, 14);

        txFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFacebookActionPerformed(evt);
            }
        });
        jpContacto.add(txFacebook);
        txFacebook.setBounds(490, 40, 130, 25);

        CancelarButton.add(jpContacto);
        jpContacto.setBounds(10, 100, 640, 80);

        jpDanzas.setBorder(javax.swing.BorderFactory.createTitledBorder("Danzas"));
        jpDanzas.setLayout(null);

        tbDanzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Danzas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spDanzas.setViewportView(tbDanzas);

        jpDanzas.add(spDanzas);
        spDanzas.setBounds(350, 30, 280, 110);
        jpDanzas.add(txDanza);
        txDanza.setBounds(10, 40, 160, 25);

        etDanza.setText("Agregue las danzas que conozca el profesor");
        jpDanzas.add(etDanza);
        etDanza.setBounds(10, 20, 310, 14);

        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        jpDanzas.add(btAgregar);
        btAgregar.setBounds(180, 40, 71, 23);

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        jpDanzas.add(btEliminar);
        btEliminar.setBounds(260, 40, 80, 23);

        CancelarButton.add(jpDanzas);
        jpDanzas.setBounds(10, 190, 640, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txTelCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelCelActionPerformed

    private void txApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txApellidoMaternoActionPerformed

    private void txNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNombreActionPerformed

    private void txFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFacebookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFacebookActionPerformed

    private void txTelCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelCasaActionPerformed

    private void txCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCorreoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro desea cancelar?", 
            "Cancelar alta de profesor", JOptionPane.YES_NO_OPTION);
        //Si se decide cancelar la accion, se cerrará la ventana
        if( opcion == 0 ) {
            dispose();
        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txApellidoPaternoActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        //Se crea un arrayList que contendra las danzas ingresadas
        ArrayList<String> danzasIngresadas = new ArrayList<>();
        //Se ingresa
        for ( int x = 0 ; x < tbDanzas.getRowCount(); x++) {
            danzasIngresadas.add( ( String ) tbDanzas.getValueAt( x, 0 ) );
        }
        
        try {
            boolean paso = control.alta(txNombre.getText(), txApellidoPaterno.getText(),
                    txApellidoMaterno.getText(), txTelCasa.getText(), 
                    txTelCel.getText(),txCorreo.getText(), txFacebook.getText(),
                    danzasIngresadas);
            if( paso == true ) {
                dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(VAltaProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAceptarActionPerformed

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        String danza = txDanza.getText();
        control.agregarFilasTablaDanzas( tbDanzas, danza );
    }//GEN-LAST:event_btAgregarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        fila = tbDanzas.getSelectedRow();
        if( fila != -1 ) {
            control.eliminarFilasTablaDanzas( tbDanzas, fila );
            fila = -1;
        }
    }//GEN-LAST:event_btEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAltaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAltaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAltaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAltaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    VAltaProfesor alta = new VAltaProfesor();
                    alta.setVisible(true);
                    alta.setLocationRelativeTo(null);
                } catch (SQLException ex) {
                    Logger.getLogger(VAltaProfesor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(VAltaProfesor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CancelarButton;
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JLabel etApellidoMaterno;
    private javax.swing.JLabel etApellidoPaterno;
    private javax.swing.JLabel etCorreo;
    private javax.swing.JLabel etDanza;
    private javax.swing.JLabel etFacebook;
    private javax.swing.JLabel etNombre;
    private javax.swing.JLabel etNumProfesor;
    private javax.swing.JLabel etTelefonoCasa;
    private javax.swing.JLabel etTelefonoCelular;
    private javax.swing.JPanel jpContacto;
    private javax.swing.JPanel jpDanzas;
    private javax.swing.JPanel jpNombreCompleto;
    private javax.swing.JScrollPane spDanzas;
    private javax.swing.JTable tbDanzas;
    private javax.swing.JTextField txApellidoMaterno;
    private javax.swing.JTextField txApellidoPaterno;
    private javax.swing.JTextField txCorreo;
    private javax.swing.JTextField txDanza;
    private javax.swing.JTextField txFacebook;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txNumProfesor;
    private javax.swing.JTextField txTelCasa;
    private javax.swing.JTextField txTelCel;
    // End of variables declaration//GEN-END:variables

    public void actualizaTablaDanzas( JTable tbDanzas ) {
        this.tbDanzas = tbDanzas;
    }

    public void cargaNuevoNumero(int numero) {
        txNumProfesor.setText( Integer.toString( numero ) );
    }

}
