/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CVistaCurso;
import Interfaces.ICierraVentana;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import Interfaces.ICargaProfesores;

/**
 *
 * @author Dave Went
 */
public class VAsignarProfesorACurso extends javax.swing.JFrame implements ICargaProfesores, ICierraVentana{
    CVistaCurso control;
    String nombreCurso;
    int fila = -1;
    
    public VAsignarProfesorACurso( String curso ) throws SQLException, Exception {
        initComponents();
        nombreCurso = curso;
        etCursoActual.setText( curso );
        setResizable( false );
        setLocationRelativeTo( null );
        control = new CVistaCurso( this, this );
        control.obtenerProfesores( cbProfesores, "" );
        control.obtenerProfesoresPorCurso(tbProfesores, nombreCurso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpProfesores = new javax.swing.JPanel();
        cbProfesores = new javax.swing.JComboBox<>();
        btAgregar = new javax.swing.JButton();
        btQuitar = new javax.swing.JButton();
        spProfesores = new javax.swing.JScrollPane();
        tbProfesores = new javax.swing.JTable();
        etCursoActual = new javax.swing.JLabel();
        etCurso = new javax.swing.JLabel();
        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 280));
        setMinimumSize(new java.awt.Dimension(480, 280));
        setPreferredSize(new java.awt.Dimension(480, 280));
        setResizable(false);
        getContentPane().setLayout(null);

        jpProfesores.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignar profesor"));
        jpProfesores.setLayout(null);

        cbProfesores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpProfesores.add(cbProfesores);
        cbProfesores.setBounds(10, 50, 200, 20);

        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        jpProfesores.add(btAgregar);
        btAgregar.setBounds(220, 50, 71, 23);

        btQuitar.setText("Quitar");
        btQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitarActionPerformed(evt);
            }
        });
        jpProfesores.add(btQuitar);
        btQuitar.setBounds(300, 50, 73, 23);

        tbProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. profesor", "Nombre", "Apellido paterno", "Apellido materno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProfesoresMouseClicked(evt);
            }
        });
        spProfesores.setViewportView(tbProfesores);

        jpProfesores.add(spProfesores);
        spProfesores.setBounds(10, 90, 430, 100);

        etCursoActual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpProfesores.add(etCursoActual);
        etCursoActual.setBounds(70, 20, 350, 17);

        etCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etCurso.setText("Curso:");
        jpProfesores.add(etCurso);
        etCurso.setBounds(20, 20, 60, 17);

        getContentPane().add(jpProfesores);
        jpProfesores.setBounds(10, 10, 450, 200);

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btAceptar);
        btAceptar.setBounds(240, 220, 90, 25);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar);
        btCancelar.setBounds(140, 220, 90, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que desea cancelar?", 
            "Borrado de profesor", JOptionPane.YES_NO_OPTION);
        if( opcion == 0 ) {
            dispose();
        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        int numProfesor = cbProfesores.getSelectedIndex();
        String nombreProfesor = (String) cbProfesores.getSelectedItem();
        try {
            control.agregarProfesoresEnAsignacion( tbProfesores, nombreProfesor, numProfesor );
        } catch (SQLException ex) {
            Logger.getLogger(VAsignarProfesorACurso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAgregarActionPerformed

    private void btQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitarActionPerformed
        if( fila != -1 ) {
            control.quitarProfesoresEnAsignacion( tbProfesores, fila );
            fila = -1;
        }
    }//GEN-LAST:event_btQuitarActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        try {
            control.relacionarProfesorYCurso( tbProfesores, nombreCurso );
        } catch (Exception ex) {
            Logger.getLogger(VAsignarProfesorACurso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAceptarActionPerformed

    private void tbProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProfesoresMouseClicked
        fila = tbProfesores.rowAtPoint( evt.getPoint() );
    }//GEN-LAST:event_tbProfesoresMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btQuitar;
    private javax.swing.JComboBox<String> cbProfesores;
    private javax.swing.JLabel etCurso;
    private javax.swing.JLabel etCursoActual;
    private javax.swing.JPanel jpProfesores;
    private javax.swing.JScrollPane spProfesores;
    private javax.swing.JTable tbProfesores;
    // End of variables declaration//GEN-END:variables

    public void actualizaProfesores(JComboBox cbProfesor) {
        cbProfesores = cbProfesor;
    }

    public void insertarProfesoresEnTabla(JTable tbProfesores) {
        this.tbProfesores = tbProfesores;
    }

    public void cerrarVentana() {
        dispose();
    }
}
