package Vista;

import Controlador.CVistaCicloEscolar;
import Interfaces.ICierraVentana;
import Interfaces.IRecibeDatosUsuario;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jean Antoine Maupomé Polanco
 */
public class VCicloEscolar extends javax.swing.JFrame implements Interfaces.ICicloEscolar, ICierraVentana {

    private Controlador.CCicloEscolar control;
    private CVistaCicloEscolar controlVista;

    /**
     * Crea nuevo form CicloEscolar
     */
    public VCicloEscolar() {
        initComponents();
        initComponents2();
        controlVista = new CVistaCicloEscolar(this, this);
        this.setTitle("Ciclo Escolar");
        // 
        //  actualizarModificaciones();
    }

    public void initComponents2() {
        btCrearCiclo.setEnabled(false);
        // Transformar fecha a Español
        dcCrearInicio.setLocale(new java.util.Locale("es", "ES"));
        // Transformar fecha a formato día/mes/año
        dcCrearInicio.setDateFormatString("d/MMM/yyyy");
        // El proceso es repetido para cada JDateChooser
        dcCrearFinal.setLocale(new java.util.Locale("es", "ES"));
        dcCrearFinal.setDateFormatString("d/MMM/yyyy");
        dcCrearFinal.setEnabled(false);
        dcCrearInicio.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent e) {
                dcCrearInicioPropert(e);
            }
        });
        dcCrearFinal.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent e) {
                dcCrearFinPropert(e);
            }
        });
    }

    public void dcCrearInicioPropert(PropertyChangeEvent pe) {

        if (pe.getPropertyName().compareTo("date") == 0) {

            try {
                controlVista.validarFechaInicioCrear(dcCrearInicio.getDate(),dcCrearFinal.getDate());
            } catch (ParseException ex) {
                Logger.getLogger(VCicloEscolar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    public void dcCrearFinPropert(PropertyChangeEvent pe) {
        if (pe.getPropertyName().compareTo("date") == 0) {

            controlVista.validarFechaFin(dcCrearInicio.getDate(), dcCrearFinal.getDate());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpSelectorFlujos = new javax.swing.JTabbedPane();
        jpCrearCiclo = new javax.swing.JPanel();
        btCrearCiclo = new javax.swing.JButton();
        btCancelarCreacion = new javax.swing.JButton();
        jpDuracionCicloC = new javax.swing.JPanel();
        etFechaInicioC = new javax.swing.JLabel();
        etFechaFinC = new javax.swing.JLabel();
        dcCrearInicio = new com.toedter.calendar.JDateChooser();
        dcCrearFinal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btCrearCiclo.setText("Crear ciclo");
        btCrearCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearCicloActionPerformed(evt);
            }
        });

        btCancelarCreacion.setText("Cancelar");
        btCancelarCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarCreacionActionPerformed(evt);
            }
        });

        jpDuracionCicloC.setBorder(javax.swing.BorderFactory.createTitledBorder("Duración del ciclo"));

        etFechaInicioC.setText("Fecha de inicio:");

        etFechaFinC.setText("Fecha de fin:");

        dcCrearInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcCrearInicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpDuracionCicloCLayout = new javax.swing.GroupLayout(jpDuracionCicloC);
        jpDuracionCicloC.setLayout(jpDuracionCicloCLayout);
        jpDuracionCicloCLayout.setHorizontalGroup(
            jpDuracionCicloCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDuracionCicloCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dcCrearInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(dcCrearFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpDuracionCicloCLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(etFechaInicioC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etFechaFinC)
                .addGap(45, 45, 45))
        );
        jpDuracionCicloCLayout.setVerticalGroup(
            jpDuracionCicloCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDuracionCicloCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDuracionCicloCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFechaInicioC)
                    .addComponent(etFechaFinC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDuracionCicloCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcCrearInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcCrearFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpCrearCicloLayout = new javax.swing.GroupLayout(jpCrearCiclo);
        jpCrearCiclo.setLayout(jpCrearCicloLayout);
        jpCrearCicloLayout.setHorizontalGroup(
            jpCrearCicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCrearCicloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelarCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btCrearCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jpCrearCicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDuracionCicloC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpCrearCicloLayout.setVerticalGroup(
            jpCrearCicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCrearCicloLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jpDuracionCicloC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jpCrearCicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelarCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCrearCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        tpSelectorFlujos.addTab("Crear ciclo escolar", jpCrearCiclo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpSelectorFlujos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpSelectorFlujos)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dcCrearInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcCrearInicioMouseClicked

    }//GEN-LAST:event_dcCrearInicioMouseClicked

    private void btCancelarCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarCreacionActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelarCreacionActionPerformed

    private void btCrearCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearCicloActionPerformed
        try {
            // La variable result permite indicar como terminó la creación
            // del ciclo escolar
            controlVista.crearCiclo(dcCrearInicio.getDate(), dcCrearFinal.getDate());

        } catch (Exception ex) {
            // En caso de ya exista un ciclo actualmente, no se podrá crear
            // ya que comparten el mismo nombre. Para eso se necesita editar el
            // ciclo actual.
            Logger.getLogger(VCicloEscolar.class.getName()).log(Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ya se encuentra un ciclo escolar en progreso."
                + "\nPara editar éste ciclo, seleccione "
                + "\"Modificar ciclo escolar\"", "Error de Ciclo",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCrearCicloActionPerformed
    /**
     * actualizarModificaciones permite mostrar en las modificaciones las fechas
     * del ciclo actual en caso de que se desee modificar
     */
 

    @Override
    public void enviarFechaInicio(Date hoy, boolean valida) {
        if (!valida && hoy!=null) {
            dcCrearInicio.setDate(hoy);
        }
        if(!valida && hoy==null){
            ((JTextField) dcCrearInicio.getDateEditor().getUiComponent()).setText("");
            btCrearCiclo.setEnabled(false);
        }
        dcCrearFinal.setEnabled(true);
             
    }

    @Override
    public void enviarFechaFin(boolean valida) {
        System.out.println("entreeeee");
        if (!valida) {
            ((JTextField) dcCrearFinal.getDateEditor().getUiComponent()).setText("");

        }

        btCrearCiclo.setEnabled(valida);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCicloEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCicloEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCicloEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCicloEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCicloEscolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarCreacion;
    private javax.swing.JButton btCrearCiclo;
    private com.toedter.calendar.JDateChooser dcCrearFinal;
    private com.toedter.calendar.JDateChooser dcCrearInicio;
    private javax.swing.JLabel etFechaFinC;
    private javax.swing.JLabel etFechaInicioC;
    private javax.swing.JPanel jpCrearCiclo;
    private javax.swing.JPanel jpDuracionCicloC;
    private javax.swing.JTabbedPane tpSelectorFlujos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void enviarCicloEscolar(Date fechaInicio, Date fechaFin, String nombre) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void enviarFechaFin(Date hoy, boolean valida) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void cerrarVentana() {
        dispose();
    }

}
