package Vista;

import Controlador.CVistaProfesor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import Interfaces.IConsultaProfesores;

/**
 *
 * @author Dave Went
 */
public class VConsultaProfesores extends javax.swing.JFrame implements IConsultaProfesores{

    CVistaProfesor control;
    int fila = -1;
    ButtonGroup gbBuscar;
    /**
     * Creates new form ConsultaProfesores
     */
    public VConsultaProfesores() throws Exception {
        initComponents();
        control = new CVistaProfesor( this, tbConsultas );
        control.consulta( "consulta", null);
        gbBuscar = new ButtonGroup();
        gbBuscar.add( rbMatricula );
        gbBuscar.add( rbNombre );
        rbMatricula.setSelected( true );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpProfesores = new javax.swing.JPanel();
        spConsultas = new javax.swing.JScrollPane();
        tbConsultas = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        etBuscar = new javax.swing.JLabel();
        txBuscar = new javax.swing.JTextField();
        jpTipoBusqueda = new javax.swing.JPanel();
        rbMatricula = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de profesores");

        jPanel1.setLayout(null);

        jpProfesores.setBorder(javax.swing.BorderFactory.createTitledBorder("Profesores"));
        jpProfesores.setLayout(null);

        tbConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbConsultasMouseClicked(evt);
            }
        });
        spConsultas.setViewportView(tbConsultas);

        jpProfesores.add(spConsultas);
        spConsultas.setBounds(10, 20, 900, 200);

        jPanel1.add(jpProfesores);
        jpProfesores.setBounds(10, 70, 920, 230);

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btEditar);
        btEditar.setBounds(370, 310, 90, 30);

        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btBorrar);
        btBorrar.setBounds(470, 310, 90, 30);

        etBuscar.setText("Buscar:");
        jPanel1.add(etBuscar);
        etBuscar.setBounds(20, 10, 110, 14);

        txBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txBuscar);
        txBuscar.setBounds(20, 30, 130, 25);

        jpTipoBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de búsqueda"));
        jpTipoBusqueda.setLayout(null);

        rbMatricula.setText("Número");
        jpTipoBusqueda.add(rbMatricula);
        rbMatricula.setBounds(10, 25, 100, 23);

        rbNombre.setText("Nombre");
        jpTipoBusqueda.add(rbNombre);
        rbNombre.setBounds(110, 25, 90, 23);

        jPanel1.add(jpTipoBusqueda);
        jpTipoBusqueda.setBounds(190, 10, 210, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        if( fila > -1 ) {
            String nombre = ( String ) tbConsultas.getValueAt( fila, 1 );
            String apellidoPaterno = ( String ) tbConsultas.getValueAt( fila, 2 );
            String apellidoMaterno = ( String ) tbConsultas.getValueAt( fila, 3 );
            try {
                if( control.confirmacionBorradoProfesor(nombre, apellidoPaterno, apellidoMaterno) ) {
                    fila = -1;
                    txBuscar.setText("");
                }
            } catch (Exception ex) {
                Logger.getLogger(VConsultaProfesores.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Primero selecciona un profesor",
                null, JOptionPane.ERROR_MESSAGE, null);
           
        }
    }//GEN-LAST:event_btBorrarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if( fila > -1 ) {
            String[] datos = new String[ 3 ];
            try {
                int numProfesor = Integer.parseInt( ( String ) tbConsultas.getValueAt( fila, 0 ));
                datos[ 0 ] = (String) tbConsultas.getValueAt( fila, 1 );
                datos[ 1 ] = (String) tbConsultas.getValueAt( fila, 2 );
                datos[ 2 ] = (String) tbConsultas.getValueAt( fila, 3 );
                VModificacionProfesor modificacion = new VModificacionProfesor( control, numProfesor, datos );
                modificacion.setVisible(true);
                modificacion.setLocationRelativeTo(null);
                txBuscar.setText("");
            } catch (Exception ex) {
                Logger.getLogger(VConsultaProfesores.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Primero selecciona un profesor",
                null, JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void tbConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbConsultasMouseClicked
        fila = tbConsultas.rowAtPoint( evt.getPoint() );
    }//GEN-LAST:event_tbConsultasMouseClicked

    private void txBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarKeyReleased
        String proveniente;
        String dato = txBuscar.getText();
        if( rbMatricula.isSelected() ) {
            proveniente = "matricula";
        } else {
            proveniente = "nombre";
        }
        control.busquedaCoincidencia(proveniente, dato, txBuscar);
    }//GEN-LAST:event_txBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VConsultaProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VConsultaProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VConsultaProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VConsultaProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    VConsultaProfesores consulta = new VConsultaProfesores();
                    consulta.setVisible(true);
                    consulta.setLocationRelativeTo(null);
                } catch (Exception ex) {
                    Logger.getLogger(VConsultaProfesores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JLabel etBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpProfesores;
    private javax.swing.JPanel jpTipoBusqueda;
    private javax.swing.JRadioButton rbMatricula;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JScrollPane spConsultas;
    private javax.swing.JTable tbConsultas;
    private javax.swing.JTextField txBuscar;
    // End of variables declaration//GEN-END:variables

    public void recibeDatos( JTable ConsultasJTable ) {
        this.tbConsultas = ConsultasJTable;
    }

}
