/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CVistaUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import Interfaces.IRecibeDatosUsuario;

/**
 *
 * @author Christian
 */
public class VConsultaUsuarios extends javax.swing.JFrame implements IRecibeDatosUsuario{

    CVistaUsuario control;
    int fila = -1;
    /**
     * Creates new form GraficoConsultaUsuarios
     */
    public VConsultaUsuarios() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        control = new CVistaUsuario(this,tbConsultaUsuarios);
        control.consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etTituloConsulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaUsuarios = new javax.swing.JTable();
        btEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        etTituloConsulta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etTituloConsulta.setText("Consulta de Usuarios");
        getContentPane().add(etTituloConsulta);
        etTituloConsulta.setBounds(100, 20, 210, 22);

        tbConsultaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuarios"
            }
        ));
        tbConsultaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbConsultaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbConsultaUsuarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 50, 320, 150);

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btEliminar);
        btEliminar.setBounds(150, 210, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed

        if( fila >-1 ) {
            String nombreDeUsuario = (String) tbConsultaUsuarios.getValueAt(fila, 0);
            try {
                if( control.confirmacionBorradoUsuario( nombreDeUsuario ) ) {
                    fila = -1;
                }
            } catch (Exception ex) {
                Logger.getLogger(VConsultaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Primero selecciona un usuario",
                null, JOptionPane.ERROR_MESSAGE, null);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btEliminarActionPerformed

    private void tbConsultaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbConsultaUsuariosMouseClicked
        // TODO add your handling code here:
        fila = tbConsultaUsuarios.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tbConsultaUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VConsultaUsuarios().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VConsultaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminar;
    private javax.swing.JLabel etTituloConsulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConsultaUsuarios;
    // End of variables declaration//GEN-END:variables

    public void recibeDatos(JTable consultaUsuariosjTable) {
        this.tbConsultaUsuarios = consultaUsuariosjTable;
    }
}
