/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CVistaCurso;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import Interfaces.IHorario;

/**
 *
 * @author Dave Went
 */
public class VHorario extends javax.swing.JFrame implements IHorario {

    CVistaCurso control;
    int numSalones;
    /**
     * Creates new form Horario
     */
    public VHorario() throws Exception {
        initComponents();
        control = new CVistaCurso( this );
        control.construirHorario(tbHorario );
        setLocationRelativeTo( null );
        control.consultaNumSalones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnNumSalon = new javax.swing.JSpinner();
        etNumSalones = new javax.swing.JLabel();
        btCambiar = new javax.swing.JButton();
        spHorario = new javax.swing.JScrollPane();
        tbHorario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Horario");
        setMaximumSize(new java.awt.Dimension(990, 460));
        setMinimumSize(new java.awt.Dimension(990, 460));
        setPreferredSize(new java.awt.Dimension(990, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        spnNumSalon.setValue(2);
        getContentPane().add(spnNumSalon);
        spnNumSalon.setBounds(150, 10, 100, 25);

        etNumSalones.setText("Numero de salones : ");
        getContentPane().add(etNumSalones);
        etNumSalones.setBounds(20, 10, 120, 25);

        btCambiar.setText("Cambiar");
        btCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiarActionPerformed(evt);
            }
        });
        getContentPane().add(btCambiar);
        btCambiar.setBounds(260, 10, 90, 23);

        tbHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbHorarioMousePressed(evt);
            }
        });
        spHorario.setViewportView(tbHorario);

        getContentPane().add(spHorario);
        spHorario.setBounds(10, 40, 960, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbHorarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHorarioMousePressed
        if (evt.getClickCount() > 1) {
            Point puntero = evt.getPoint();
            int fila = tbHorario.rowAtPoint( puntero );
            int columna = tbHorario.columnAtPoint( puntero );
            if( columna != 0 ) {
                String nombreCurso = ( String ) tbHorario.getValueAt( fila, 0 );
                VClases clases;
                try {
                    clases = new VClases( control, nombreCurso, columna, numSalones, tbHorario );
                    clases.setVisible( true );
                    clases.setLocationRelativeTo( null );
                } catch (Exception ex) {
                    Logger.getLogger(VHorario.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        }
    }//GEN-LAST:event_tbHorarioMousePressed

    private void btCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambiarActionPerformed
        try {
            int nuevoNumSalones = ( int ) spnNumSalon.getValue();
            control.actualizaSalones( nuevoNumSalones, numSalones );
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VHorario().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VHorario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCambiar;
    private javax.swing.JLabel etNumSalones;
    private javax.swing.JScrollPane spHorario;
    private javax.swing.JSpinner spnNumSalon;
    private javax.swing.JTable tbHorario;
    // End of variables declaration//GEN-END:variables

    public void recibeCursosYClases( JTable tbHorario ) {
        this.tbHorario = tbHorario;
    }

    public void recibeSalones( int numSalones ) {
        spnNumSalon.setValue( numSalones );
        this.numSalones = numSalones;
    }
}
