/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Christian
 */
public class VLogin extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */
    public VLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etUsuario = new javax.swing.JLabel();
        etContraseña = new javax.swing.JLabel();
        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        etOlvidoContraseña = new javax.swing.JLabel();
        pfContraseña = new javax.swing.JPasswordField();
        etInicioSesion = new javax.swing.JLabel();
        txUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(290, 245));
        getContentPane().setLayout(null);

        etUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        etUsuario.setText("Usuario: ");
        getContentPane().add(etUsuario);
        etUsuario.setBounds(40, 60, 50, 17);

        etContraseña.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        etContraseña.setText("Contraseña: ");
        getContentPane().add(etContraseña);
        etContraseña.setBounds(20, 110, 70, 17);

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btAceptar);
        btAceptar.setBounds(160, 170, 90, 30);

        btCancelar.setText("Cancelar");
        getContentPane().add(btCancelar);
        btCancelar.setBounds(40, 170, 90, 30);

        etOlvidoContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etOlvidoContraseña.setText("¿Olvidaste tu contraseña?");
        etOlvidoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etOlvidoContraseñaMouseClicked(evt);
            }
        });
        getContentPane().add(etOlvidoContraseña);
        etOlvidoContraseña.setBounds(120, 140, 141, 15);
        getContentPane().add(pfContraseña);
        pfContraseña.setBounds(110, 100, 152, 30);

        etInicioSesion.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        etInicioSesion.setText("Inicio de Sesión");
        getContentPane().add(etInicioSesion);
        etInicioSesion.setBounds(80, 10, 130, 24);

        txUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txUsuario);
        txUsuario.setBounds(110, 50, 152, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etOlvidoContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etOlvidoContraseñaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_etOlvidoContraseñaMouseClicked

    private void txUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txUsuarioActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JLabel etContraseña;
    private javax.swing.JLabel etInicioSesion;
    private javax.swing.JLabel etOlvidoContraseña;
    private javax.swing.JLabel etUsuario;
    private javax.swing.JPasswordField pfContraseña;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables

    public JButton getBtAceptar() {
        return btAceptar;
    }

    public JButton getBtCancelar() {
        return btCancelar;
    }

    public JPasswordField getPfContraseña() {
        return pfContraseña;
    }

    public JTextField getTxUsuario() {
        return txUsuario;
    }

    public void setBtAceptar(JButton btAceptar) {
        this.btAceptar = btAceptar;
    }

    public void setBtCancelar(JButton btCancelar) {
        this.btCancelar = btCancelar;
    }

    public void setPfContraseña(JPasswordField pfContraseña) {
        this.pfContraseña = pfContraseña;
    }

    public void setTxUsuario(JTextField txUsuario) {
        this.txUsuario = txUsuario;
    }
    
}
