/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CVistaCurso;
import Interfaces.ICierraVentana;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import Interfaces.IModificacionCurso;

/**
 *
 * @author DaveWent
 */
public class VModificacionCursoEspecifico extends javax.swing.JFrame implements 
        IModificacionCurso, ICierraVentana{
    CVistaCurso control;
    String activaFecha = "No";
    int fila = -1;

    /**
     * Creates new form RegistroCurso
     */
    public VModificacionCursoEspecifico( String nombreCurso ) {
        initComponents( );
        setLocationRelativeTo( null );
        jpFecha.setVisible( false );
        control = new CVistaCurso( this, this );
        control.crearVentana( nombreCurso );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCurso = new javax.swing.JPanel();
        etNombre = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        etProfesor = new javax.swing.JLabel();
        cbProfesor = new javax.swing.JComboBox();
        chTipoCurso = new javax.swing.JCheckBox();
        chSilencio = new javax.swing.JCheckBox();
        btAgregar = new javax.swing.JButton();
        btQuitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProfesores = new javax.swing.JTable();
        btAceptar = new javax.swing.JButton();
        jpFecha = new javax.swing.JPanel();
        etFechaInicio = new javax.swing.JLabel();
        etFechaFin = new javax.swing.JLabel();
        clFechaFin = new com.toedter.calendar.JDateChooser();
        clFechaInicio = new com.toedter.calendar.JDateChooser();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ModificarCurso");
        setMaximumSize(new java.awt.Dimension(633, 366));
        setMinimumSize(new java.awt.Dimension(633, 366));
        setPreferredSize(new java.awt.Dimension(633, 366));
        getContentPane().setLayout(null);

        jpCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Curso"));
        jpCurso.setLayout(null);

        etNombre.setText("Nombre del curso");
        jpCurso.add(etNombre);
        etNombre.setBounds(20, 20, 110, 14);

        txNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNombreActionPerformed(evt);
            }
        });
        jpCurso.add(txNombre);
        txNombre.setBounds(20, 40, 220, 25);

        etProfesor.setText("Profesor/es asignado/s");
        jpCurso.add(etProfesor);
        etProfesor.setBounds(270, 20, 160, 14);

        cbProfesor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","", "", "" }));
        jpCurso.add(cbProfesor);
        cbProfesor.setBounds(270, 40, 160, 25);

        chTipoCurso.setText("Es un curso esporádico");
        chTipoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chTipoCursoActionPerformed(evt);
            }
        });
        jpCurso.add(chTipoCurso);
        chTipoCurso.setBounds(20, 70, 180, 23);

        chSilencio.setText("Requiere de total silencio");
        chSilencio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSilencioActionPerformed(evt);
            }
        });
        jpCurso.add(chSilencio);
        chSilencio.setBounds(20, 90, 170, 23);

        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        jpCurso.add(btAgregar);
        btAgregar.setBounds(440, 40, 73, 23);

        btQuitar.setText("Quitar");
        btQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitarActionPerformed(evt);
            }
        });
        jpCurso.add(btQuitar);
        btQuitar.setBounds(520, 40, 73, 23);

        tbProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Profesores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProfesoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProfesores);
        if (tbProfesores.getColumnModel().getColumnCount() > 0) {
            tbProfesores.getColumnModel().getColumn(0).setResizable(false);
        }

        jpCurso.add(jScrollPane1);
        jScrollPane1.setBounds(270, 80, 310, 90);

        getContentPane().add(jpCurso);
        jpCurso.setBounds(10, 11, 610, 190);

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btAceptar);
        btAceptar.setBounds(330, 300, 90, 30);

        jpFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Duración"));
        jpFecha.setEnabled(true);
        jpFecha.setLayout(null);

        etFechaInicio.setText("Fecha de inicio");
        jpFecha.add(etFechaInicio);
        etFechaInicio.setBounds(20, 20, 100, 14);

        etFechaFin.setText("Fecha de fin");
        jpFecha.add(etFechaFin);
        etFechaFin.setBounds(310, 20, 100, 14);
        jpFecha.add(clFechaFin);
        clFechaFin.setBounds(310, 40, 220, 25);
        jpFecha.add(clFechaInicio);
        clFechaInicio.setBounds(20, 40, 220, 25);

        getContentPane().add(jpFecha);
        jpFecha.setBounds(10, 210, 610, 80);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar);
        btCancelar.setBounds(230, 300, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNombreActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        String nombreCurso = txNombre.getText();
        String tipoCurso;
        if( chTipoCurso.isSelected() == true ) {
            tipoCurso = "esporadico";
        } else {
            tipoCurso = "normal";
        }
        String silencio;
        if( chSilencio.isSelected() == true ) {
            silencio = "SI";
        } else {
            silencio = "NO";
        }
        String formato = clFechaInicio.getDateFormatString();
        Date fechaInicio = clFechaInicio.getDate();
        Date fechaFin = clFechaFin.getDate();
        control.modificacion(nombreCurso, tipoCurso, silencio, formato, fechaInicio, fechaFin);
    }//GEN-LAST:event_btAceptarActionPerformed

    private void chTipoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chTipoCursoActionPerformed
        if( activaFecha.equals( "No" ) ) {
            activaFecha = "Si";
            jpFecha.setVisible( true );
        } else {
            activaFecha = "No";
            jpFecha.setVisible( false );
        }
    }//GEN-LAST:event_chTipoCursoActionPerformed

    private void chSilencioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSilencioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chSilencioActionPerformed

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        int numProfesor = cbProfesor.getSelectedIndex();
        String nombreProfesor = (String) cbProfesor.getSelectedItem();
        control.agregarFilasATablaProfesores( tbProfesores, nombreProfesor, numProfesor );
//        control.agregarFilasATablaProfesores( numProfesor, nombreProfesor, tbProfesores );
    }//GEN-LAST:event_btAgregarActionPerformed

    private void btQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitarActionPerformed
        if( fila != -1 ) {
            control.eliminarFilasATablaProfesores( tbProfesores );
            fila = -1;
        }
    }//GEN-LAST:event_btQuitarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que desea cancelar?", 
            "Borrado de profesor", JOptionPane.YES_NO_OPTION);
        if( opcion == 0 ) {
            dispose();
        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tbProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProfesoresMouseClicked
        fila = tbProfesores.rowAtPoint( evt.getPoint() );
    }//GEN-LAST:event_tbProfesoresMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btQuitar;
    private javax.swing.JComboBox cbProfesor;
    private javax.swing.JCheckBox chSilencio;
    private javax.swing.JCheckBox chTipoCurso;
    private com.toedter.calendar.JDateChooser clFechaFin;
    private com.toedter.calendar.JDateChooser clFechaInicio;
    private javax.swing.JLabel etFechaFin;
    private javax.swing.JLabel etFechaInicio;
    private javax.swing.JLabel etNombre;
    private javax.swing.JLabel etProfesor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpCurso;
    private javax.swing.JPanel jpFecha;
    private javax.swing.JTable tbProfesores;
    private javax.swing.JTextField txNombre;
    // End of variables declaration//GEN-END:variables

    public void creaVentanaModificacion( String[] curso ) {
        String nombreCurso = curso[ 0 ];
        String tipo = curso[ 1 ];
        String requiereSilencio = curso[ 2 ];
        String fechaInicio = curso[ 3 ];
        String fechaFin = curso[ 4 ];
        txNombre.setText( nombreCurso );
        if( requiereSilencio.equalsIgnoreCase( "Si" ) ) {
            chSilencio.setSelected( true );
        }
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            if( tipo.equalsIgnoreCase( "esporadico" ) ) {
                fechaDate = formatoFecha.parse( fechaInicio );
                clFechaInicio.setDate( fechaDate );
                fechaDate = formatoFecha.parse( fechaFin );
                clFechaFin.setDate( fechaDate );
            }
            String proveniente = "modificacion";
            control.obtenerProfesores( cbProfesor, proveniente);
            control.insertarProfesoresEnTabla( tbProfesores, nombreCurso );
        } catch ( ParseException ex ) {
            ex.printStackTrace();
        } catch (Exception ex) { 
            ex.printStackTrace();
        }
        if( tipo.equals( "esporadico" ) ) {
            chTipoCurso.setSelected( true );
            activaFecha = "Si";
            jpFecha.setVisible( true );
        } else {
            clFechaInicio.setDate( null );
            clFechaFin.setDate( null );
        }
    }

    public void recibeProfesoresEnComboBox( JComboBox cbProfesor ) {
        this.cbProfesor = cbProfesor;
    }

    public void recibeProfesoresEnTabla( JTable tbProfesores ) {
        this.tbProfesores = tbProfesores;
    }

    public void actualizaTabla( JTable tbProfesores ) {
        this.tbProfesores = tbProfesores;
    }

    public void cerrarVentana() {
        dispose();
    }

    
}
