/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CVistaCicloEscolar;
import Interfaces.ICierraVentana;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author cristian
 */
public class VModificarCicloEscolar extends javax.swing.JFrame implements 
        Interfaces.ICicloEscolar, ICierraVentana {

    /**
     * Creates new form VistaModificarCicloEscolar
     */
    private Controlador.CVistaCicloEscolar controlVista;

    public VModificarCicloEscolar() {

        initComponents();

        controlVista = new CVistaCicloEscolar(this,this);
        controlVista.ConsultarCicloEscolar();
        initCompenents2();
    }

    public void initCompenents2() {
        //btCrearCiclo.setEnabled(false);
        // Transformar fecha a Español
        dcEditarInicio.setLocale(new java.util.Locale("es", "ES"));
        // Transformar fecha a formato día/mes/año
        dcEditarInicio.setDateFormatString("d/MMM/yyyy");
        // El proceso es repetido para cada JDateChooser
        dcEditarFinal.setLocale(new java.util.Locale("es", "ES"));
        dcEditarFinal.setDateFormatString("d/MMM/yyyy");
        dcEditarInicio.setLocale(new java.util.Locale("es", "ES"));
        dcEditarInicio.setDateFormatString("d/MMM/yyyy");
        dcEditarFinal.setLocale(new java.util.Locale("es", "ES"));
        dcEditarFinal.setDateFormatString("d/MMM/yyyy");

        dcEditarInicio.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent e) {
                dcModifInicioPropert(e);
            }
        });
        dcEditarFinal.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent e) {
                dcModifFinPropert(e);
            }
        });
    }

    public void dcModifInicioPropert(PropertyChangeEvent pe) {

        if (pe.getPropertyName().compareTo("date") == 0) {

            controlVista.validarFechaInicio(dcEditarInicio.getDate(), dcEditarFinal.getDate());

        }
    }

    public void dcModifFinPropert(PropertyChangeEvent pe) {
        if (pe.getPropertyName().compareTo("date") == 0) {

            controlVista.validarFechaFinM(dcEditarInicio.getDate(), dcEditarFinal.getDate());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCicloActual = new javax.swing.JPanel();
        lbNombreCiclo = new javax.swing.JLabel();
        jpDuracionCicloM = new javax.swing.JPanel();
        etFechaInicioM = new javax.swing.JLabel();
        etFechaFinM = new javax.swing.JLabel();
        dcEditarInicio = new com.toedter.calendar.JDateChooser();
        dcEditarFinal = new com.toedter.calendar.JDateChooser();
        btGuardarCambios = new javax.swing.JButton();
        btCancelarModif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpCicloActual.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciclo escolar actual"));

        lbNombreCiclo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNombreCiclo.setText("Ciclo20018-1");

        javax.swing.GroupLayout jpCicloActualLayout = new javax.swing.GroupLayout(jpCicloActual);
        jpCicloActual.setLayout(jpCicloActualLayout);
        jpCicloActualLayout.setHorizontalGroup(
            jpCicloActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCicloActualLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(lbNombreCiclo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCicloActualLayout.setVerticalGroup(
            jpCicloActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCicloActualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNombreCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDuracionCicloM.setBorder(javax.swing.BorderFactory.createTitledBorder("Duración del ciclo"));

        etFechaInicioM.setText("Fecha de inicio:");

        etFechaFinM.setText("Fecha de fin:");

        dcEditarInicio.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                dcEditarInicioInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jpDuracionCicloMLayout = new javax.swing.GroupLayout(jpDuracionCicloM);
        jpDuracionCicloM.setLayout(jpDuracionCicloMLayout);
        jpDuracionCicloMLayout.setHorizontalGroup(
            jpDuracionCicloMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDuracionCicloMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dcEditarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dcEditarFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpDuracionCicloMLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(etFechaInicioM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etFechaFinM)
                .addGap(45, 45, 45))
        );
        jpDuracionCicloMLayout.setVerticalGroup(
            jpDuracionCicloMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDuracionCicloMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDuracionCicloMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFechaInicioM)
                    .addComponent(etFechaFinM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDuracionCicloMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcEditarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcEditarFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btGuardarCambios.setText("Guardar Cambios");
        btGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarCambiosActionPerformed(evt);
            }
        });

        btCancelarModif.setText("Cancelar");
        btCancelarModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarModifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(79, Short.MAX_VALUE)
                        .addComponent(btCancelarModif, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btGuardarCambios)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpCicloActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpDuracionCicloM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jpCicloActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jpDuracionCicloM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelarModif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dcEditarInicioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dcEditarInicioInputMethodTextChanged

    }//GEN-LAST:event_dcEditarInicioInputMethodTextChanged

    private void btGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarCambiosActionPerformed

        controlVista.Modifica(dcEditarInicio.getDate(), dcEditarFinal.getDate());

    }//GEN-LAST:event_btGuardarCambiosActionPerformed

    private void btCancelarModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarModifActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btCancelarModifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VModificarCicloEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VModificarCicloEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VModificarCicloEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VModificarCicloEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VModificarCicloEscolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarModif;
    private javax.swing.JButton btGuardarCambios;
    private com.toedter.calendar.JDateChooser dcEditarFinal;
    private com.toedter.calendar.JDateChooser dcEditarInicio;
    private javax.swing.JLabel etFechaFinM;
    private javax.swing.JLabel etFechaInicioM;
    private javax.swing.JPanel jpCicloActual;
    private javax.swing.JPanel jpDuracionCicloM;
    private javax.swing.JLabel lbNombreCiclo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void enviarCicloEscolar(Date fechaInicio, Date fechaFin, String nombre) {
        lbNombreCiclo.setText(nombre);
        dcEditarInicio.setDate(fechaInicio);
        dcEditarFinal.setDate(fechaFin);
    }

    @Override
    public void enviarFechaInicio(Date fechaInicio, boolean valida) {

        dcEditarInicio.setDate(fechaInicio);
        dcEditarInicio.setEnabled(valida);
    }

    @Override
    public void enviarFechaFin(boolean valida) {
        if (!valida) {
               ((JTextField) dcEditarFinal.getDateEditor().getUiComponent()).setText("");
        }
        btGuardarCambios.setEnabled(valida);
    }

    @Override
    public void enviarFechaFin(Date fechaFin, boolean valida) {
        dcEditarFinal.setDate(fechaFin);
    }

    public void cerrarVentana() {
        dispose();
    }
}
