package Vista;

import Controlador.CVistaProfesor;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import Interfaces.IModificacionProfesor;

/**
 *
 * @author Daid Omar Cabrera Bernal
 */
public class VModificacionProfesor extends javax.swing.JFrame implements IModificacionProfesor{

    CVistaProfesor controlConsulta;
    CVistaProfesor controlModificacion;
    int fila = -1;
    String[] nombreCompleto;
    /**
     * Creates new form AltaProfesores
     */
    public VModificacionProfesor( CVistaProfesor control, int numProfesor,String[] datos ) 
            throws Exception {
        initComponents();
        this.controlConsulta = control;
        controlModificacion = new CVistaProfesor(this);
        controlModificacion.insertarEnVentana( numProfesor, datos, cbCursos );
        nombreCompleto = datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCancelar = new javax.swing.JButton();
        btAceptar = new javax.swing.JButton();
        jpNombre = new javax.swing.JPanel();
        etNombre = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        txApellidoPaterno = new javax.swing.JTextField();
        etApellidoPaterno = new javax.swing.JLabel();
        etApellido = new javax.swing.JLabel();
        txApellidoMaterno = new javax.swing.JTextField();
        jpContacto = new javax.swing.JPanel();
        etTelefonoCasa = new javax.swing.JLabel();
        txTelefonoCasa = new javax.swing.JTextField();
        etTelefonoCelular = new javax.swing.JLabel();
        txTelefonoCelular = new javax.swing.JTextField();
        etCorreo = new javax.swing.JLabel();
        txCorreo = new javax.swing.JTextField();
        etFacebook = new javax.swing.JLabel();
        txFacebook = new javax.swing.JTextField();
        jpCursos = new javax.swing.JPanel();
        etCursos = new javax.swing.JLabel();
        cbCursos = new javax.swing.JComboBox();
        spCursos = new javax.swing.JScrollPane();
        tbCursos = new javax.swing.JTable();
        spDanzas = new javax.swing.JScrollPane();
        tbDanzas = new javax.swing.JTable();
        btAgregar = new javax.swing.JButton();
        btQuitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificación de profesor");

        jPanel1.setLayout(null);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btCancelar);
        btCancelar.setBounds(230, 390, 90, 30);

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btAceptar);
        btAceptar.setBounds(330, 390, 90, 30);

        jpNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre completo"));
        jpNombre.setLayout(null);

        etNombre.setText("Nombre");
        jpNombre.add(etNombre);
        etNombre.setBounds(10, 20, 50, 14);

        txNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNombreActionPerformed(evt);
            }
        });
        jpNombre.add(txNombre);
        txNombre.setBounds(10, 40, 130, 25);

        txApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txApellidoPaternoActionPerformed(evt);
            }
        });
        jpNombre.add(txApellidoPaterno);
        txApellidoPaterno.setBounds(170, 40, 130, 25);

        etApellidoPaterno.setText("Apellido Paterno");
        jpNombre.add(etApellidoPaterno);
        etApellidoPaterno.setBounds(170, 20, 90, 14);

        etApellido.setText("Apellido materno");
        jpNombre.add(etApellido);
        etApellido.setBounds(330, 20, 100, 14);

        txApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txApellidoMaternoActionPerformed(evt);
            }
        });
        jpNombre.add(txApellidoMaterno);
        txApellidoMaterno.setBounds(330, 40, 140, 25);

        jPanel1.add(jpNombre);
        jpNombre.setBounds(10, 10, 640, 80);

        jpContacto.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));
        jpContacto.setLayout(null);

        etTelefonoCasa.setText("Teléfono de casa");
        jpContacto.add(etTelefonoCasa);
        etTelefonoCasa.setBounds(10, 20, 110, 14);

        txTelefonoCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelefonoCasaActionPerformed(evt);
            }
        });
        jpContacto.add(txTelefonoCasa);
        txTelefonoCasa.setBounds(10, 40, 130, 25);

        etTelefonoCelular.setText("Teléfono Celular");
        jpContacto.add(etTelefonoCelular);
        etTelefonoCelular.setBounds(170, 20, 100, 14);

        txTelefonoCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelefonoCelularActionPerformed(evt);
            }
        });
        jpContacto.add(txTelefonoCelular);
        txTelefonoCelular.setBounds(170, 40, 130, 25);

        etCorreo.setText("Correo electrónico");
        jpContacto.add(etCorreo);
        etCorreo.setBounds(330, 20, 110, 14);

        txCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCorreoActionPerformed(evt);
            }
        });
        jpContacto.add(txCorreo);
        txCorreo.setBounds(330, 40, 140, 25);

        etFacebook.setText("Cuenta de Facebook");
        jpContacto.add(etFacebook);
        etFacebook.setBounds(490, 20, 120, 14);

        txFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFacebookActionPerformed(evt);
            }
        });
        jpContacto.add(txFacebook);
        txFacebook.setBounds(490, 40, 130, 25);

        jPanel1.add(jpContacto);
        jpContacto.setBounds(10, 100, 640, 80);

        jpCursos.setBorder(javax.swing.BorderFactory.createTitledBorder("Curso"));
        jpCursos.setLayout(null);

        etCursos.setText("Curso que imparte");
        jpCursos.add(etCursos);
        etCursos.setBounds(10, 20, 110, 20);

        cbCursos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Salsa", "Yoga", "Ballet", "Ritmos latinos" }));
        jpCursos.add(cbCursos);
        cbCursos.setBounds(10, 40, 140, 20);

        tbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Cursos que imparte"
            }
        ));
        tbCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCursosMouseClicked(evt);
            }
        });
        spCursos.setViewportView(tbCursos);
        if (tbCursos.getColumnModel().getColumnCount() > 0) {
            tbCursos.getColumnModel().getColumn(0).setResizable(false);
        }

        jpCursos.add(spCursos);
        spCursos.setBounds(10, 80, 330, 100);

        tbDanzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""},
                {""},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Danzas que conoce"
            }
        ));
        spDanzas.setViewportView(tbDanzas);
        if (tbDanzas.getColumnModel().getColumnCount() > 0) {
            tbDanzas.getColumnModel().getColumn(0).setResizable(false);
        }

        jpCursos.add(spDanzas);
        spDanzas.setBounds(370, 40, 250, 110);

        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        jpCursos.add(btAgregar);
        btAgregar.setBounds(170, 40, 71, 23);

        btQuitar.setText("Quitar");
        btQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitarActionPerformed(evt);
            }
        });
        jpCursos.add(btQuitar);
        btQuitar.setBounds(250, 40, 63, 23);

        jPanel1.add(jpCursos);
        jpCursos.setBounds(10, 190, 640, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txTelefonoCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelefonoCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelefonoCelularActionPerformed

    private void txApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txApellidoMaternoActionPerformed

    private void txNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNombreActionPerformed

    private void txFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFacebookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFacebookActionPerformed

    private void txTelefonoCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelefonoCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelefonoCasaActionPerformed

    private void txCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCorreoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que desea cancelar?", 
            "Borrado de profesor", JOptionPane.YES_NO_OPTION);
        if( opcion == 0 ) {
            dispose();
        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txApellidoPaternoActionPerformed

    private void btQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitarActionPerformed
        if( fila != -1 ) {
            String contenidoFila = (String) tbCursos.getValueAt( fila, 0 );
            controlModificacion.eliminaFilaTablaCursosModificacion(fila, contenidoFila, tbCursos );
        }
    }//GEN-LAST:event_btQuitarActionPerformed

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        controlModificacion.agregarFilaATablaCursosModificacion(( String ) cbCursos.getSelectedItem(), tbCursos);
       
    }//GEN-LAST:event_btAgregarActionPerformed

    private void tbCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCursosMouseClicked
        fila = tbCursos.rowAtPoint( evt.getPoint() );
    }//GEN-LAST:event_tbCursosMouseClicked

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        tbDanzas.clearSelection(); 
        tbCursos.clearSelection();
        ArrayList<String> danzas = new ArrayList<>();
        String danza;
        int contadorDanzas = 0;
        for ( int x = 0 ; x < 5; x++) {
            danza = ( String ) tbDanzas.getValueAt( x, 0 ) ;
            if( danza != null ) {
                if( danza.trim().length() == 0 ) {
                    contadorDanzas++;
                } else {
                    danzas.add( ( String ) tbDanzas.getValueAt( x, 0 ) );
                }
            }
            if( danza == null ) {
                contadorDanzas++;
            }
        }
        String nombre = txNombre.getText();
        String apellidoPaterno = txApellidoPaterno.getText();
        String apellidoMaterno = txApellidoMaterno.getText();
        String telefonoCasa = txTelefonoCasa.getText();
        String telefonoCelular = txTelefonoCelular.getText();
        String email = txCorreo.getText();
        String facebook = txFacebook.getText();
        controlModificacion.modificacion( nombreCompleto, nombre, apellidoPaterno, 
                apellidoMaterno,telefonoCasa, telefonoCelular, email, facebook, 
                danzas,contadorDanzas, tbCursos );
    }//GEN-LAST:event_btAceptarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btQuitar;
    private javax.swing.JComboBox cbCursos;
    private javax.swing.JLabel etApellido;
    private javax.swing.JLabel etApellidoPaterno;
    private javax.swing.JLabel etCorreo;
    private javax.swing.JLabel etCursos;
    private javax.swing.JLabel etFacebook;
    private javax.swing.JLabel etNombre;
    private javax.swing.JLabel etTelefonoCasa;
    private javax.swing.JLabel etTelefonoCelular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpContacto;
    private javax.swing.JPanel jpCursos;
    private javax.swing.JPanel jpNombre;
    private javax.swing.JScrollPane spCursos;
    private javax.swing.JScrollPane spDanzas;
    private javax.swing.JTable tbCursos;
    private javax.swing.JTable tbDanzas;
    private javax.swing.JTextField txApellidoMaterno;
    private javax.swing.JTextField txApellidoPaterno;
    private javax.swing.JTextField txCorreo;
    private javax.swing.JTextField txFacebook;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txTelefonoCasa;
    private javax.swing.JTextField txTelefonoCelular;
    // End of variables declaration//GEN-END:variables


    public void recibeDatosParaModificacion(String[] datos, String[] danzasConocidas,
            String[] cursos,JComboBox cursosJComboBox  ) {
        
        txNombre.setText( datos[ 0 ] );
        txApellidoPaterno.setText( datos[ 1 ] );
        txApellidoMaterno.setText( datos[ 2 ] );
        txTelefonoCasa.setText( datos[ 3 ] );
        txTelefonoCelular.setText( datos[ 4 ] );
        txCorreo.setText( datos[ 5 ] );
        txFacebook.setText( datos[ 6 ] );
        for( int x = 0 ; x < danzasConocidas.length ; x++ ) {
            tbDanzas.setValueAt( danzasConocidas[ x ], x, 0 );
        }
        for( int x = 0 ; x < cursos.length ; x++ ) {
            tbCursos.setValueAt( cursos[ x ], x, 0 );
        }
        this.cbCursos = cursosJComboBox;
    }

    public void recibeTablaCursos(JTable cursosJTable) {
        this.tbCursos = cursosJTable;
    }
}


