/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CVistaCostos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import Interfaces.IRecibeDatosCostos;

/**
 *
 * @author Christian
 */
public class VModificacionCostos extends javax.swing.JFrame implements 
        IRecibeDatosCostos, ItemListener,ActionListener {
jpModificacionCostoEsporadico panel;
CVistaCostos control;
    /**
     * Creates new form Grafico3
     */
    public VModificacionCostos() throws Exception {
        initComponents();
        panel=new jpModificacionCostoEsporadico();
        panel.setBounds(35, 140, 530, 380);
        panel.setVisible(false);
        getContentPane().add(panel);
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(inscripcionYMensualidadjRadioButton);
        grupo.add(cursoEsporadicojRadioButton);
        modificacionjPanel2.setVisible(false);
        control = new CVistaCostos(this);
        control.actualizacionVentana();
        panel.getCbCursos().addItemListener(this);
        panel.getBtAceptar().addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        modificacionjPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        costoInscripcionjLabel1 = new javax.swing.JLabel();
        costoInscripcionjTextField1 = new javax.swing.JTextField();
        aceptarjButton1 = new javax.swing.JButton();
        cancelarjButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        costoMensualidadjLabel2 = new javax.swing.JLabel();
        costoMensualidadjTextField2 = new javax.swing.JTextField();
        tipoDeModificacionjPanel = new javax.swing.JPanel();
        inscripcionYMensualidadjRadioButton = new javax.swing.JRadioButton();
        cursoEsporadicojRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar mensualidad, inscripción y costo de curso esporádico");
        setMaximumSize(new java.awt.Dimension(600, 570));
        setMinimumSize(new java.awt.Dimension(600, 570));
        setPreferredSize(new java.awt.Dimension(600, 570));
        setResizable(false);
        getContentPane().setLayout(null);

        modificacionjPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        modificacionjPanel2.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Inscripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(24, 90, 40, 0);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 30, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Precio Actual Inscripción:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 30, 150, 30);

        costoInscripcionjLabel1.setText("jLabel1");
        jPanel1.add(costoInscripcionjLabel1);
        costoInscripcionjLabel1.setBounds(170, 30, 60, 30);

        costoInscripcionjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoInscripcionjTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(costoInscripcionjTextField1);
        costoInscripcionjTextField1.setBounds(300, 30, 70, 30);

        modificacionjPanel2.add(jPanel1);
        jPanel1.setBounds(40, 30, 420, 90);
        jPanel1.getAccessibleContext().setAccessibleName("Modificar Inscripción, Mensualidad y Curso Esporádico");

        aceptarjButton1.setText("Aceptar");
        aceptarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarjButton1ActionPerformed(evt);
            }
        });
        modificacionjPanel2.add(aceptarjButton1);
        aceptarjButton1.setBounds(280, 270, 100, 30);

        cancelarjButton2.setText("Cancelar");
        modificacionjPanel2.add(cancelarjButton2);
        cancelarjButton2.setBounds(150, 270, 100, 30);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Mensualidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel4.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Precio Actual Mensualidad: ");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 40, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Precio:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(240, 40, 50, 30);

        costoMensualidadjLabel2.setText("jLabel1");
        jPanel4.add(costoMensualidadjLabel2);
        costoMensualidadjLabel2.setBounds(170, 40, 60, 30);
        jPanel4.add(costoMensualidadjTextField2);
        costoMensualidadjTextField2.setBounds(300, 40, 70, 30);

        modificacionjPanel2.add(jPanel4);
        jPanel4.setBounds(40, 140, 420, 110);

        getContentPane().add(modificacionjPanel2);
        modificacionjPanel2.setBounds(50, 140, 500, 330);

        tipoDeModificacionjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elije el tipo de modificación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        tipoDeModificacionjPanel.setLayout(null);

        inscripcionYMensualidadjRadioButton.setText("Inscripción y Mensualidad");
        inscripcionYMensualidadjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscripcionYMensualidadjRadioButtonActionPerformed(evt);
            }
        });
        tipoDeModificacionjPanel.add(inscripcionYMensualidadjRadioButton);
        inscripcionYMensualidadjRadioButton.setBounds(70, 30, 170, 30);

        cursoEsporadicojRadioButton.setText("Curso Esporádico");
        cursoEsporadicojRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoEsporadicojRadioButtonActionPerformed(evt);
            }
        });
        tipoDeModificacionjPanel.add(cursoEsporadicojRadioButton);
        cursoEsporadicojRadioButton.setBounds(290, 30, 140, 30);

        getContentPane().add(tipoDeModificacionjPanel);
        tipoDeModificacionjPanel.setBounds(40, 30, 520, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarjButton1ActionPerformed
        // TODO add your handling code here:
     String precioDeLaCaja=costoInscripcionjTextField1.getText();
    String precioDeLaEtiqueta=costoInscripcionjLabel1.getText();
    
    if(!precioDeLaCaja.equalsIgnoreCase("")){
        try {
        control.ActualizarCostos("Inscripcion", precioDeLaEtiqueta, precioDeLaCaja);
    } catch (Exception ex) {
        Logger.getLogger(VModificacionCostos.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }
    
         String precioDeLaCaja2=costoMensualidadjTextField2.getText();
    String precioDeLaEtiqueta2=costoMensualidadjLabel2.getText();
    
            if(!precioDeLaCaja2.equalsIgnoreCase("")){
                try {
        control.ActualizarCostos("Mensualidad", precioDeLaEtiqueta2, precioDeLaCaja2);
    } catch (Exception ex) {
        Logger.getLogger(VModificacionCostos.class.getName()).log(Level.SEVERE, null, ex);
    }
    
            }
    
    }//GEN-LAST:event_aceptarjButton1ActionPerformed

    private void costoInscripcionjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoInscripcionjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoInscripcionjTextField1ActionPerformed

    private void cursoEsporadicojRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoEsporadicojRadioButtonActionPerformed
        
        panel.setVisible(true);
        modificacionjPanel2.setVisible(false);
    try {
        control.obtenerCurso(panel.getCbCursos());
    } catch (Exception ex) {
        Logger.getLogger(VModificacionCostos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_cursoEsporadicojRadioButtonActionPerformed

    private void inscripcionYMensualidadjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscripcionYMensualidadjRadioButtonActionPerformed
        // TODO add your handling code here:
             panel.setVisible(false);
        modificacionjPanel2.setVisible(true);
    }//GEN-LAST:event_inscripcionYMensualidadjRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VModificacionCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VModificacionCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VModificacionCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VModificacionCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VModificacionCostos().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VModificacionCostos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarjButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cancelarjButton2;
    private javax.swing.JLabel costoInscripcionjLabel1;
    private javax.swing.JTextField costoInscripcionjTextField1;
    private javax.swing.JLabel costoMensualidadjLabel2;
    private javax.swing.JTextField costoMensualidadjTextField2;
    private javax.swing.JRadioButton cursoEsporadicojRadioButton;
    private javax.swing.JRadioButton inscripcionYMensualidadjRadioButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel modificacionjPanel2;
    private javax.swing.JPanel tipoDeModificacionjPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void RecibeDatos(String precio, String valor) {
    costoInscripcionjLabel1.setText(precio);
    costoMensualidadjLabel2.setText(valor);
    }

    @Override
    public void RecibeCursos(JComboBox cbCursos) {
       panel.setCbCursos(cbCursos);
    }

    @Override
    public void RecibeCostoEsporadico(String costoEsporadico) {
        panel.getEtCosto().setText(costoEsporadico);
    }

    @Override
    public void itemStateChanged(ItemEvent ie) {
        if (ie.getSource()==panel.getCbCursos()){
        String seleccionado=(String)panel.getCbCursos().getSelectedItem();
            try {
                control.obtenerCostoEsporadico(seleccionado);
            } catch (SQLException ex) {
                Logger.getLogger(VModificacionCostos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
      
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource()==panel.getBtAceptar()){
            String precioDeLaCaja=panel.getTxCostoEsporadico().getText();
            String precioDeLaEtiqueta=panel.getEtCosto().getText();
            String cursoEsporadico = (String) panel.getCbCursos().getSelectedItem();
            if( !cursoEsporadico.equalsIgnoreCase("Seleccione un curso") ) {
                if(!precioDeLaCaja.equalsIgnoreCase("")){
                try {
                    control.ActualizarCostos(cursoEsporadico, precioDeLaEtiqueta, precioDeLaCaja);
                } catch (Exception ex) {
                    Logger.getLogger(VModificacionCostos.class.getName()).log(Level.SEVERE, null, ex);
                }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecciona un curso", null, 
                    JOptionPane.ERROR_MESSAGE, null);
            }
            
            
        }
    }
}
