/**
 * VPrincipal.java
 * Version 3
 * 1/05/2016
 * Copyright (c) Wiscorp Mexicali,BC
 * All rights reserved
 */
package Vista;

import Controlador.CVistaPrincipal;
import Controlador.CVistaUsuario;
import com.alee.laf.WebLookAndFeel;
import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Clase que contiene la vista principal y los metodos para invocar las demas
 * vistas que componen el sistema
 * @author David Omar Cabrera Bernal
 */
public class VPrincipal extends javax.swing.JFrame implements ActionListener{
    
    CVistaPrincipal controlPrincipal;
    CVistaUsuario controlUsuario;
    VPrimerRegistroUsuario registro;
    VLogin login;

    /**
     * Constructor que inicializa la vista principal
     * @throws Exception 
     */
    public VPrincipal() throws Exception {
        initComponents();
        setLocationRelativeTo( null );
        setResizable( false );
        controlPrincipal = new CVistaPrincipal();
        controlUsuario = new CVistaUsuario();
        registro = new VPrimerRegistroUsuario();
        login = new VLogin();
        registro.getBtAceptar().addActionListener(this);
        registro.getBtCancelar().addActionListener(this);
        login.getBtAceptar().addActionListener(this);
        login.getBtCancelar().addActionListener(this);
        inicioSistema();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMenus = new javax.swing.JTabbedPane();
        jpAlumnado = new javax.swing.JPanel();
        btAgregarAlumno = new javax.swing.JButton(new ImageIcon( this.getClass().getResource( "/Iconos/AgregarAlumno.png" ) ));
        btConsultaAlumnos = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/consultaAlumnos.png" ) ) );
        btRegistrarAsistencias = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/registrarAsistencias.png" ) ) );
        btReinscripcion = new javax.swing.JButton(new ImageIcon( this.getClass().getResource( "/Iconos/reinscripcion.png" ) ) );
        jpCursos = new javax.swing.JPanel();
        btNuevoCiclo = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/nuevoCiclo.png" ) ) );
        btExtenderCiclo = new javax.swing.JButton(new ImageIcon( this.getClass().getResource( "/Iconos/extenderCiclo.png" ) ));
        btAgregarCurso = new javax.swing.JButton(new ImageIcon( this.getClass().getResource( "/Iconos/agregarCurso.png" ) ));
        btModificarCurso = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/modificarCurso.png" ) ) );
        btBorrarCurso = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/borrarCurso.png" ) ) );
        btHorario = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/horario.png" ) ) );
        btAgregarProfesor = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/agregarProfesor.png" ) ) );
        btConsultaProfesores = new javax.swing.JButton(new ImageIcon( this.getClass().getResource( "/Iconos/consultaProfesores.png" ) ));
        btEstadisticas = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/estadisticas.png" ) ) );
        btAsignarprofesor = new javax.swing.JButton(new ImageIcon( this.getClass().getResource( "/Iconos/asignarProfesor.png" ) ));
        jpPagos = new javax.swing.JPanel();
        btRegistrarPagos = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/registrarPagos.png" ) ) );
        btConsultaPagos = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/consultaPagos.png" ) ) );
        btConsultaAdeudos = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/consultaAdeudos.png" ) ) );
        btModificarCostos = new javax.swing.JButton(new ImageIcon( this.getClass().getResource( "/Iconos/modificacionCostos.png" ) ));
        jpUsuarios = new javax.swing.JPanel();
        btAgregarUsuario = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/agregarUsuario.png" ) )  );
        btConsultaUsuarios = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/consultaUsuarios.png" ) ) );
        btHistorialCambios = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/historialCambios.png" ) ) );
        btCerrarSesion = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/cerrarSesion.png" ) ) );
        btFondo = new javax.swing.JButton( new ImageIcon( this.getClass().getResource( "/Iconos/fondo.png" ) ) );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tanz Studio 3.0");
        setMaximumSize(new java.awt.Dimension(884, 650));
        setMinimumSize(new java.awt.Dimension(884, 650));
        setPreferredSize(new java.awt.Dimension(970, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jtpMenus.setPreferredSize(new java.awt.Dimension(900, 140));

        btAgregarAlumno.setMaximumSize(new java.awt.Dimension(85, 85));
        btAgregarAlumno.setMinimumSize(new java.awt.Dimension(85, 85));
        btAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarAlumnoActionPerformed(evt);
            }
        });

        btConsultaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaAlumnosActionPerformed(evt);
            }
        });

        btRegistrarAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarAsistenciasActionPerformed(evt);
            }
        });

        btReinscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReinscripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAlumnadoLayout = new javax.swing.GroupLayout(jpAlumnado);
        jpAlumnado.setLayout(jpAlumnadoLayout);
        jpAlumnadoLayout.setHorizontalGroup(
            jpAlumnadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAgregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRegistrarAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btReinscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(585, Short.MAX_VALUE))
        );
        jpAlumnadoLayout.setVerticalGroup(
            jpAlumnadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAlumnadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btReinscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegistrarAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jtpMenus.addTab("Gestión de alumnado", jpAlumnado);

        btNuevoCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoCicloActionPerformed(evt);
            }
        });

        btExtenderCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExtenderCicloActionPerformed(evt);
            }
        });

        btAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCursoActionPerformed(evt);
            }
        });

        btModificarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarCursoActionPerformed(evt);
            }
        });

        btBorrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarCursoActionPerformed(evt);
            }
        });

        btHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHorarioActionPerformed(evt);
            }
        });

        btAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarProfesorActionPerformed(evt);
            }
        });

        btConsultaProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaProfesoresActionPerformed(evt);
            }
        });

        btEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstadisticasActionPerformed(evt);
            }
        });

        btAsignarprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsignarprofesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCursosLayout = new javax.swing.GroupLayout(jpCursos);
        jpCursos.setLayout(jpCursosLayout);
        jpCursosLayout.setHorizontalGroup(
            jpCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNuevoCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExtenderCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btModificarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBorrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAsignarprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultaProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpCursosLayout.setVerticalGroup(
            jpCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAsignarprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultaProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBorrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExtenderCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNuevoCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jtpMenus.addTab("Gestión de cursos", jpCursos);

        btRegistrarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarPagosActionPerformed(evt);
            }
        });

        btConsultaPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaPagosActionPerformed(evt);
            }
        });

        btConsultaAdeudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaAdeudosActionPerformed(evt);
            }
        });

        btModificarCostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarCostosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPagosLayout = new javax.swing.GroupLayout(jpPagos);
        jpPagos.setLayout(jpPagosLayout);
        jpPagosLayout.setHorizontalGroup(
            jpPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btRegistrarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultaPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultaAdeudos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btModificarCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(585, Short.MAX_VALUE))
        );
        jpPagosLayout.setVerticalGroup(
            jpPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btModificarCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultaAdeudos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultaPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegistrarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jtpMenus.addTab("Gestión de pagos", jpPagos);

        jpUsuarios.setToolTipText("");

        btAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarUsuarioActionPerformed(evt);
            }
        });

        btConsultaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaUsuariosActionPerformed(evt);
            }
        });

        btHistorialCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistorialCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpUsuariosLayout = new javax.swing.GroupLayout(jpUsuarios);
        jpUsuarios.setLayout(jpUsuariosLayout);
        jpUsuariosLayout.setHorizontalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btHistorialCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );
        jpUsuariosLayout.setVerticalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btHistorialCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jtpMenus.addTab("Gestión de usuarios", jpUsuarios);

        getContentPane().add(jtpMenus);
        jtpMenus.setBounds(0, 30, 970, 140);

        btCerrarSesion.setToolTipText("");
        btCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btCerrarSesion);
        btCerrarSesion.setBounds(840, 10, 110, 25);

        btFondo.setBorder(null);
        btFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFondoActionPerformed(evt);
            }
        });
        getContentPane().add(btFondo);
        btFondo.setBounds(-10, 160, 980, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCerrarSesionActionPerformed

    private void btAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarAlumnoActionPerformed
        try {
            VInscripcion inscripcion = new VInscripcion();
            inscripcion.setVisible(true);
            inscripcion.setLocationRelativeTo( null );
            inscripcion.setResizable( false );
        } catch (Exception ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAgregarAlumnoActionPerformed

    private void btConsultaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaAlumnosActionPerformed
        VConsulta consultaAlumnos = new VConsulta();
        consultaAlumnos.setVisible(true);
        consultaAlumnos.setLocationRelativeTo( null );
        consultaAlumnos.setResizable( false );
    }//GEN-LAST:event_btConsultaAlumnosActionPerformed

    private void btRegistrarAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarAsistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegistrarAsistenciasActionPerformed

    private void btReinscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReinscripcionActionPerformed
        VConsultaReinscripcion reinscripcion = new VConsultaReinscripcion();
        reinscripcion.setVisible(true);
        reinscripcion.setLocationRelativeTo( null );
        reinscripcion.setResizable( false );
    }//GEN-LAST:event_btReinscripcionActionPerformed

    private void btAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarUsuarioActionPerformed
        VRegistroUsuario registrarUsuario = new VRegistroUsuario();
        registrarUsuario.setVisible(true);
        registrarUsuario.setLocationRelativeTo( null );
        registrarUsuario.setResizable( false );
    }//GEN-LAST:event_btAgregarUsuarioActionPerformed

    private void btConsultaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaUsuariosActionPerformed
        VConsultaUsuarios VConsultaUsuario;
        try {
            VConsultaUsuario = new VConsultaUsuarios();
            VConsultaUsuario.setVisible(true);
            VConsultaUsuario.setLocationRelativeTo( null );
            VConsultaUsuario.setResizable( false );
        } catch (Exception ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConsultaUsuariosActionPerformed

    private void btHistorialCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistorialCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHistorialCambiosActionPerformed

    private void btNuevoCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoCicloActionPerformed
        VCicloEscolar cicloEscolar = new VCicloEscolar();
        cicloEscolar.setVisible(true);
        cicloEscolar.setLocationRelativeTo( null );
        cicloEscolar.setResizable( false );
    }//GEN-LAST:event_btNuevoCicloActionPerformed

    private void btExtenderCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExtenderCicloActionPerformed
        try {
            VModificarCicloEscolar modifCiclo = new VModificarCicloEscolar();
            modifCiclo.setVisible(true);
            modifCiclo.setLocationRelativeTo( null );
            modifCiclo.setResizable( false );
        }catch( NullPointerException e) {
            JOptionPane.showMessageDialog( null, "Primero creee un ciclo escolar",
                    null, JOptionPane.ERROR_MESSAGE, null);
        }
        
    }//GEN-LAST:event_btExtenderCicloActionPerformed

    private void btAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarProfesorActionPerformed
        VAltaProfesor altaProfesor;
        try {
            altaProfesor = new VAltaProfesor();
            altaProfesor.setVisible(true);
            altaProfesor.setLocationRelativeTo( null );
            altaProfesor.setResizable( false );
        } catch (Exception ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btAgregarProfesorActionPerformed

    private void btConsultaProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaProfesoresActionPerformed
        try {
            VConsultaProfesores consultaProfesores = new VConsultaProfesores();
            consultaProfesores.setVisible(true);
            consultaProfesores.setLocationRelativeTo( null );
            consultaProfesores.setResizable( false );
        } catch (Exception ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btConsultaProfesoresActionPerformed

    private void btAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCursoActionPerformed
        try {
            VAltaCurso altaCurso = new VAltaCurso();
            altaCurso.setVisible( true );
            altaCurso.setLocationRelativeTo( null );
            altaCurso.setResizable( false );
        } catch (SQLException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAgregarCursoActionPerformed

    private void btModificarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarCursoActionPerformed
        VModificacionCursos modificacionCurso;
        try {
            modificacionCurso = new VModificacionCursos();
            modificacionCurso.setVisible( true );
            modificacionCurso.setLocationRelativeTo( null );
            modificacionCurso.setResizable( false );
        } catch (Exception ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btModificarCursoActionPerformed

    private void btBorrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarCursoActionPerformed
        try {
            VBajaCurso bajaCurso = new VBajaCurso();
            bajaCurso.setVisible( true );
            bajaCurso.setLocationRelativeTo( null );
            bajaCurso.setResizable( false );
        } catch (Exception ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBorrarCursoActionPerformed

    private void btFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFondoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFondoActionPerformed

    private void btAsignarprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsignarprofesorActionPerformed
        try {
            VSeleccionCurso seleccionCurso = new VSeleccionCurso();
            seleccionCurso.setVisible( true );
            seleccionCurso.setLocationRelativeTo( null );
            seleccionCurso.setResizable( false );
        } catch (Exception ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAsignarprofesorActionPerformed

    private void btHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHorarioActionPerformed
        try {
            VHorario horario = new VHorario();
            horario.setVisible( true );
            horario.setLocationRelativeTo( null );
            horario.setResizable( false );
        } catch (Exception ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btHorarioActionPerformed

    private void btEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstadisticasActionPerformed
        VEstadisticas estadisticas;
        try {
            estadisticas = new VEstadisticas();
            estadisticas.setVisible( true );
            estadisticas.setLocationRelativeTo( null );
            estadisticas.setResizable( false );
        } catch (SQLException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btEstadisticasActionPerformed

    private void btModificarCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarCostosActionPerformed
        try {
            VModificacionCostos modifCostos = new VModificacionCostos();
            modifCostos.setVisible( true );
            modifCostos.setLocationRelativeTo( null );
            modifCostos.setResizable( false );
        } catch (Exception ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btModificarCostosActionPerformed

    private void btRegistrarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarPagosActionPerformed
        VRegistroPagos registroPagos = new VRegistroPagos();
        registroPagos.setVisible( true );
        registroPagos.setLocationRelativeTo( null );
        registroPagos.setResizable( false );
    }//GEN-LAST:event_btRegistrarPagosActionPerformed

    private void btConsultaPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaPagosActionPerformed
        VConsultaPagos consultaPagos = new VConsultaPagos();
        consultaPagos.setVisible( true );
        consultaPagos.setLocationRelativeTo( null );
        consultaPagos.setResizable( false );
    }//GEN-LAST:event_btConsultaPagosActionPerformed

    private void btConsultaAdeudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaAdeudosActionPerformed
        VConsultaAdeudos consultaAdeudos = new VConsultaAdeudos();
        consultaAdeudos.setVisible( true );
        consultaAdeudos.setLocationRelativeTo( null );
        consultaAdeudos.setResizable( false );
    }//GEN-LAST:event_btConsultaAdeudosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    JFrame.setDefaultLookAndFeelDecorated(true);
                    JDialog.setDefaultLookAndFeelDecorated(true);                  
                        UIManager.setLookAndFeel( new AcrylLookAndFeel());
                } catch (Exception e) {
                    try {
                        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    } catch (Exception ex) {
                        Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }
                try {
                    new VPrincipal();
                } catch (Exception ex) {
                    Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private void inicioSistema() throws Exception {
        boolean existencia = controlPrincipal.verificarUsuariosExistentes();
        if( existencia == false ) {
            registro.setVisible( true );
            registro.setLocationRelativeTo(null);
            registro.setResizable( false );
        } else {
            login.setVisible( true );
            login.setLocationRelativeTo(null);
            login.setResizable( false );
        }
    }
    
    public void actionPerformed(ActionEvent ae) {
        if( ae.getSource() == registro.getBtAceptar() ) {
            String nombreUsuario = registro.getTxUsuario().getText();
            String contraseña = registro.getTxContraseña().getText();
            String confirmacionContraseña =
                   registro.getTxContraseñaConfirmacion().getText();
            String pregunta = (String) registro.getCbPregunta().getSelectedItem();
            String respuesta = registro.getTxRespuesta().getText();
            String tipo = "administradorPrincipal";
            try {
                boolean pase = controlUsuario.altas(nombreUsuario, contraseña, contraseña, 
                       pregunta, respuesta, tipo, "primeraVez");
                if( pase == true ) {
                    registro.dispose();
                    setVisible(true );
                }
            } catch (Exception ex) {
            }
        }
       
        if( ae.getSource() == registro.getBtCancelar() ) {
           System.exit(0);
        }
        
        if( ae.getSource() == login.getBtAceptar() ) {
            String nombre = login.getTxUsuario().getText();
            String contraseña = login.getPfContraseña().getText();
            try {
                boolean pase = controlUsuario.iniciarSesion(nombre, contraseña);
                if( pase == true ) {
                    login.dispose();
                    setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario y contraseña incorrectos",
                            null, JOptionPane.ERROR_MESSAGE, null);
                }
            } catch (SQLException ex) {
            } catch (Exception ex) {
                Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if( ae.getSource() == login.getBtCancelar() ) {
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarAlumno;
    private javax.swing.JButton btAgregarCurso;
    private javax.swing.JButton btAgregarProfesor;
    private javax.swing.JButton btAgregarUsuario;
    private javax.swing.JButton btAsignarprofesor;
    private javax.swing.JButton btBorrarCurso;
    private javax.swing.JButton btCerrarSesion;
    private javax.swing.JButton btConsultaAdeudos;
    private javax.swing.JButton btConsultaAlumnos;
    private javax.swing.JButton btConsultaPagos;
    private javax.swing.JButton btConsultaProfesores;
    private javax.swing.JButton btConsultaUsuarios;
    private javax.swing.JButton btEstadisticas;
    private javax.swing.JButton btExtenderCiclo;
    private javax.swing.JButton btFondo;
    private javax.swing.JButton btHistorialCambios;
    private javax.swing.JButton btHorario;
    private javax.swing.JButton btModificarCostos;
    private javax.swing.JButton btModificarCurso;
    private javax.swing.JButton btNuevoCiclo;
    private javax.swing.JButton btRegistrarAsistencias;
    private javax.swing.JButton btRegistrarPagos;
    private javax.swing.JButton btReinscripcion;
    private javax.swing.JPanel jpAlumnado;
    private javax.swing.JPanel jpCursos;
    private javax.swing.JPanel jpPagos;
    private javax.swing.JPanel jpUsuarios;
    private javax.swing.JTabbedPane jtpMenus;
    // End of variables declaration//GEN-END:variables
}
