/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlVistaPagos;
import Interfaces.InterfaceRecibeDatosPagos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class VRegistroPagos extends javax.swing.JFrame implements InterfaceRecibeDatosPagos{
    ControlVistaPagos control;
    String tipo;
    /**
     * Creates new form RegistroPagosGrafico
     */
    public VRegistroPagos() {
        initComponents();
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(rbInscripcion);
        grupo.add(rbMensualidad);
        grupo.add(rbEsporadico);
        
        ButtonGroup grupoBusqueda = new ButtonGroup();
        grupoBusqueda.add(rbMatricula);
        grupoBusqueda.add(rbNombre);
        
        rbMensualidad.setSelected(true);
        cbCursoEsporadico.setVisible(false);
        jpRegistrarPago.setVisible(true);
        jpRecibo.setVisible(false);
         txMatriculaNombre.setVisible(false);
         txApellidoPaterno.setVisible(false);
         txApellidoMaterno.setVisible(false);
         control = new ControlVistaPagos(this);
         tipo = "mensualidad";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTipoDePago = new javax.swing.JPanel();
        rbInscripcion = new javax.swing.JRadioButton();
        rbMensualidad = new javax.swing.JRadioButton();
        rbEsporadico = new javax.swing.JRadioButton();
        jpRegistrarPago = new javax.swing.JPanel();
        jpRecibo = new javax.swing.JPanel();
        etNumeroRecibo = new javax.swing.JLabel();
        etNumeroDelRecibo = new javax.swing.JLabel();
        etMatricula = new javax.swing.JLabel();
        etMatriculaEnRecibo = new javax.swing.JLabel();
        etFecha = new javax.swing.JLabel();
        etFechaEnRecibo = new javax.swing.JLabel();
        etNombre = new javax.swing.JLabel();
        etNombreEnRecibo = new javax.swing.JLabel();
        etPagado = new javax.swing.JLabel();
        etPagadoEnRecibo = new javax.swing.JLabel();
        etMulta = new javax.swing.JLabel();
        etAdeudo = new javax.swing.JLabel();
        etAdeudoEnRecibo = new javax.swing.JLabel();
        etHora = new javax.swing.JLabel();
        etHoraDelRecibo = new javax.swing.JLabel();
        etMultaEnRecibo = new javax.swing.JLabel();
        jpBusqueda = new javax.swing.JPanel();
        rbMatricula = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        txApellidoMaterno = new javax.swing.JTextField();
        txMatriculaNombre = new javax.swing.JTextField();
        txApellidoPaterno = new javax.swing.JTextField();
        btBuscarAlumno = new javax.swing.JButton();
        cbCursoEsporadico = new javax.swing.JComboBox();
        etAbono = new javax.swing.JLabel();
        txAbono = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Pagos");
        setMaximumSize(new java.awt.Dimension(690, 570));
        setMinimumSize(new java.awt.Dimension(690, 570));
        setPreferredSize(new java.awt.Dimension(690, 570));

        jpTipoDePago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione Tipo de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jpTipoDePago.setLayout(null);

        rbInscripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbInscripcion.setText("Inscripción");
        rbInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInscripcionActionPerformed(evt);
            }
        });
        jpTipoDePago.add(rbInscripcion);
        rbInscripcion.setBounds(60, 30, 110, 30);

        rbMensualidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbMensualidad.setText("Mensualidad");
        rbMensualidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMensualidadActionPerformed(evt);
            }
        });
        jpTipoDePago.add(rbMensualidad);
        rbMensualidad.setBounds(230, 30, 100, 30);

        rbEsporadico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbEsporadico.setText("Esporádico");
        rbEsporadico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEsporadicoActionPerformed(evt);
            }
        });
        jpTipoDePago.add(rbEsporadico);
        rbEsporadico.setBounds(410, 30, 100, 30);

        jpRegistrarPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pago de Mensualidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jpRecibo.setBorder(javax.swing.BorderFactory.createTitledBorder("Recibo"));

        etNumeroRecibo.setText("No.");

        etMatricula.setText("Matrícula:");

        etFecha.setText("Fecha:");

        etNombre.setText("Nombre:");

        etPagado.setText("Pagado:");

        etMulta.setText("Multa:");

        etAdeudo.setText("Adeudo:");

        etHora.setText("Hora:");

        javax.swing.GroupLayout jpReciboLayout = new javax.swing.GroupLayout(jpRecibo);
        jpRecibo.setLayout(jpReciboLayout);
        jpReciboLayout.setHorizontalGroup(
            jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReciboLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpReciboLayout.createSequentialGroup()
                        .addComponent(etNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etNombreEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(jpReciboLayout.createSequentialGroup()
                        .addGroup(jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpReciboLayout.createSequentialGroup()
                                .addComponent(etNumeroRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(etNumeroDelRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpReciboLayout.createSequentialGroup()
                                .addComponent(etMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etMatriculaEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpReciboLayout.createSequentialGroup()
                                .addComponent(etHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(etHoraDelRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(169, 169, 169))
                            .addGroup(jpReciboLayout.createSequentialGroup()
                                .addComponent(etFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etFechaEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))))
                    .addGroup(jpReciboLayout.createSequentialGroup()
                        .addGroup(jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpReciboLayout.createSequentialGroup()
                                .addComponent(etMulta)
                                .addGap(18, 18, 18)
                                .addComponent(etMultaEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196))
                            .addGroup(jpReciboLayout.createSequentialGroup()
                                .addComponent(etPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etPagadoEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(etAdeudo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etAdeudoEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jpReciboLayout.setVerticalGroup(
            jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReciboLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etNumeroDelRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etNumeroRecibo)
                    .addComponent(etFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etFechaEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etMatriculaEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etHora)
                    .addComponent(etHoraDelRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etNombreEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etPagado)
                    .addComponent(etPagadoEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etAdeudo)
                    .addComponent(etAdeudoEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jpReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etMulta)
                    .addComponent(etMultaEnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda por:"));
        jpBusqueda.setLayout(null);

        rbMatricula.setText("Matrícula");
        rbMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMatriculaActionPerformed(evt);
            }
        });
        jpBusqueda.add(rbMatricula);
        rbMatricula.setBounds(20, 30, 100, 23);

        rbNombre.setText("Nombre");
        rbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNombreActionPerformed(evt);
            }
        });
        jpBusqueda.add(rbNombre);
        rbNombre.setBounds(120, 30, 100, 23);

        txApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txApellidoMaternoActionPerformed(evt);
            }
        });
        jpBusqueda.add(txApellidoMaterno);
        txApellidoMaterno.setBounds(30, 140, 160, 30);

        txMatriculaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMatriculaNombreActionPerformed(evt);
            }
        });
        txMatriculaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txMatriculaNombreKeyReleased(evt);
            }
        });
        jpBusqueda.add(txMatriculaNombre);
        txMatriculaNombre.setBounds(30, 60, 160, 30);

        txApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txApellidoPaternoActionPerformed(evt);
            }
        });
        jpBusqueda.add(txApellidoPaterno);
        txApellidoPaterno.setBounds(30, 100, 160, 30);

        btBuscarAlumno.setText("Buscar");
        btBuscarAlumno.setPreferredSize(new java.awt.Dimension(100, 30));
        btBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarAlumnoActionPerformed(evt);
            }
        });
        jpBusqueda.add(btBuscarAlumno);
        btBuscarAlumno.setBounds(60, 240, 100, 30);

        cbCursoEsporadico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un curso" }));
        cbCursoEsporadico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursoEsporadicoActionPerformed(evt);
            }
        });
        jpBusqueda.add(cbCursoEsporadico);
        cbCursoEsporadico.setBounds(30, 190, 160, 40);

        etAbono.setText("Abono:");

        txAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txAbonoKeyReleased(evt);
            }
        });

        btCancelar.setText("Cancelar");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btImprimir.setText("Imprimir");

        javax.swing.GroupLayout jpRegistrarPagoLayout = new javax.swing.GroupLayout(jpRegistrarPago);
        jpRegistrarPago.setLayout(jpRegistrarPagoLayout);
        jpRegistrarPagoLayout.setHorizontalGroup(
            jpRegistrarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistrarPagoLayout.createSequentialGroup()
                .addGroup(jpRegistrarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistrarPagoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jpBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRegistrarPagoLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRegistrarPagoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(etAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jpRegistrarPagoLayout.setVerticalGroup(
            jpRegistrarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistrarPagoLayout.createSequentialGroup()
                .addGroup(jpRegistrarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistrarPagoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jpRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                    .addGroup(jpRegistrarPagoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jpRegistrarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpRegistrarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jpTipoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jpTipoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpRegistrarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txApellidoMaternoActionPerformed

    private void txMatriculaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMatriculaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMatriculaNombreActionPerformed

    private void txApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txApellidoPaternoActionPerformed

    private void rbInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInscripcionActionPerformed
        // TODO add your handling code here:       
        cbCursoEsporadico.setVisible(false);
        jpRegistrarPago.setVisible(true);
        jpRegistrarPago.setBorder(javax.swing.BorderFactory.createTitledBorder(
                null, "Pago de inscripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
                javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                new java.awt.Font("Tahoma", 1, 12)));
        tipo = "inscripcion";
        
    }//GEN-LAST:event_rbInscripcionActionPerformed

    private void rbMensualidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMensualidadActionPerformed
        // TODO add your handling code here:
        cbCursoEsporadico.setVisible(false);
        jpRegistrarPago.setVisible(true);
        jpRegistrarPago.setBorder(javax.swing.BorderFactory.createTitledBorder(
                null, "Pago de mensualidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
                javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                new java.awt.Font("Tahoma", 1, 12))); 
        tipo = "mensualidad";
    }//GEN-LAST:event_rbMensualidadActionPerformed

    private void rbEsporadicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEsporadicoActionPerformed
        // TODO add your handling code here:
        cbCursoEsporadico.setVisible(true);
        jpRegistrarPago.setVisible(true);
        jpRegistrarPago.setBorder(javax.swing.BorderFactory.createTitledBorder(
                null, "Pago de curso esporádico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
                javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                new java.awt.Font("Tahoma", 1, 12)));
        tipo = "esporadico";
    }//GEN-LAST:event_rbEsporadicoActionPerformed

    private void rbMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMatriculaActionPerformed
    txMatriculaNombre.setVisible(true);
    txApellidoPaterno.setVisible(false);
    txApellidoMaterno.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMatriculaActionPerformed

    private void rbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNombreActionPerformed
         txMatriculaNombre.setVisible(true);
         txApellidoPaterno.setVisible(true);
         txApellidoMaterno.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNombreActionPerformed

    private void txAbonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txAbonoKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_txAbonoKeyReleased

    private void txMatriculaNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txMatriculaNombreKeyReleased
        
    }//GEN-LAST:event_txMatriculaNombreKeyReleased

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        
        if( tipo.equalsIgnoreCase("inscripcion") || tipo.equalsIgnoreCase("mensualidad") ) {
            control.guardarRecibo(tipo,etNumeroDelRecibo.getText(), etMatriculaEnRecibo.getText(),
                etNombreEnRecibo.getText(), etPagadoEnRecibo.getText(), etAdeudoEnRecibo.getText(),
                etMultaEnRecibo.getText(), txAbono.getText());
        } else {
            String curso = (String) cbCursoEsporadico.getSelectedItem();
            if( !curso.equalsIgnoreCase("Seleccione un curso") ) {
                tipo = (String) cbCursoEsporadico.getSelectedItem();
                control.guardarRecibo(tipo,etNumeroDelRecibo.getText(), etMatriculaEnRecibo.getText(),
                etNombreEnRecibo.getText(), etPagadoEnRecibo.getText(), etAdeudoEnRecibo.getText(),
                etMultaEnRecibo.getText(), txAbono.getText());
            }
        }
        
        if( tipo.equalsIgnoreCase("inscripcion") ) {
            control.busquedaConMatricula(etMatriculaEnRecibo.getText(), tipo);
        } else {
            if( tipo.equalsIgnoreCase("mensualidad") ) {
                control.busquedaConMatriculaMensualidad(etMatriculaEnRecibo.getText(), tipo);
            } else {
                String curso = (String) cbCursoEsporadico.getSelectedItem();
                if( !curso.equalsIgnoreCase("Seleccione un curso") ) {
                    int matricula = Integer.parseInt( txMatriculaNombre.getText() );
                    try {
                        control.obtenerCostosCurso( curso, matricula);
                    } catch (Exception ex) {
                        Logger.getLogger(VRegistroPagos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
        }
        //
        txAbono.setText("");
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarAlumnoActionPerformed
        jpRecibo.setVisible(false);
        if(rbMatricula.isSelected()){
             String matricula = txMatriculaNombre.getText();
            try {
                if(tipo.equalsIgnoreCase( "Inscripcion" ) ){
                    control.busquedaConMatricula(matricula, tipo);
                }
                else{
                    if(tipo.equalsIgnoreCase( "esporadico" ) ){
                        control.busquedaEsporadicoPorMatricula( matricula, cbCursoEsporadico );
                    } else {
                        control.busquedaConMatriculaMensualidad( matricula, tipo );
                    }
                    
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                Logger.getLogger(VRegistroPagos.class.getName()).log(Level.SEVERE, null, ex);

            }
        }else {
            String nombre=txMatriculaNombre.getText();
            String apellidoPaterno=txApellidoPaterno.getText();
            String apellidoMaterno=txApellidoMaterno.getText();
            
            if(rbMensualidad.isSelected()){
            control.busquedaConNombreCompleto(nombre, apellidoPaterno, apellidoMaterno,tipo);
            }else{
            control.busquedaEsporadicoPorNombre(nombre, apellidoPaterno, apellidoMaterno, cbCursoEsporadico);
            }
                 
        }
    }//GEN-LAST:event_btBuscarAlumnoActionPerformed

    private void cbCursoEsporadicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursoEsporadicoActionPerformed
        String curso = (String) cbCursoEsporadico.getSelectedItem();
        int matricula = Integer.parseInt( etMatriculaEnRecibo.getText() );
        try {
            if(!curso.equalsIgnoreCase("Seleccione un curso") ) {
                control.obtenerCostosCurso( curso, matricula);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(VRegistroPagos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbCursoEsporadicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRegistroPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRegistroPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRegistroPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRegistroPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VRegistroPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarAlumno;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JComboBox cbCursoEsporadico;
    private javax.swing.JLabel etAbono;
    private javax.swing.JLabel etAdeudo;
    private javax.swing.JLabel etAdeudoEnRecibo;
    private javax.swing.JLabel etFecha;
    private javax.swing.JLabel etFechaEnRecibo;
    private javax.swing.JLabel etHora;
    private javax.swing.JLabel etHoraDelRecibo;
    private javax.swing.JLabel etMatricula;
    private javax.swing.JLabel etMatriculaEnRecibo;
    private javax.swing.JLabel etMulta;
    private javax.swing.JLabel etMultaEnRecibo;
    private javax.swing.JLabel etNombre;
    private javax.swing.JLabel etNombreEnRecibo;
    private javax.swing.JLabel etNumeroDelRecibo;
    private javax.swing.JLabel etNumeroRecibo;
    private javax.swing.JLabel etPagado;
    private javax.swing.JLabel etPagadoEnRecibo;
    private javax.swing.JPanel jpBusqueda;
    private javax.swing.JPanel jpRecibo;
    private javax.swing.JPanel jpRegistrarPago;
    private javax.swing.JPanel jpTipoDePago;
    private javax.swing.JRadioButton rbEsporadico;
    private javax.swing.JRadioButton rbInscripcion;
    private javax.swing.JRadioButton rbMatricula;
    private javax.swing.JRadioButton rbMensualidad;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JTextField txAbono;
    private javax.swing.JTextField txApellidoMaterno;
    private javax.swing.JTextField txApellidoPaterno;
    private javax.swing.JTextField txMatriculaNombre;
    // End of variables declaration//GEN-END:variables

    public void BusquedaPorMatricula(String[] alumnoMatricula, ArrayList<String> cuenta) {
        String nombreCompleto = alumnoMatricula[1] +" "+ alumnoMatricula[2] +" "+ alumnoMatricula[3];
        etNombreEnRecibo.setText(nombreCompleto);
        etMatriculaEnRecibo.setText(alumnoMatricula[0]);
        etNumeroDelRecibo.setText(cuenta.get(0));
        etPagadoEnRecibo.setText(cuenta.get(1));
        double costo = Double.parseDouble(cuenta.get(2));
        double saldo = Double.parseDouble(cuenta.get(1));
        double adeudo = costo - saldo;
        etAdeudoEnRecibo.setText(Double.toString(adeudo));
        etMultaEnRecibo.setText(cuenta.get(3));
        jpRecibo.setVisible(true);
    }

    public void actualizaDatosAlumnoEnEsporadico(String[] datos, JComboBox cbCursos ) {
        String nombreCompleto = datos[ 1 ] + " "+ datos[ 2 ] +" "+ datos[ 3 ];
        etNombreEnRecibo.setText(nombreCompleto);
        etMatriculaEnRecibo.setText(datos[ 0 ]);
        cbCursoEsporadico = cbCursos;
        jpRecibo.setVisible(true);
    }

    public void actualizarCostos(ArrayList<String> cuenta) {
        etNumeroDelRecibo.setText(cuenta.get(0));
        etPagadoEnRecibo.setText(cuenta.get(1));
        double costo = Double.parseDouble(cuenta.get(2));
        double saldo = Double.parseDouble(cuenta.get(1));
        double adeudo = costo - saldo;
        etAdeudoEnRecibo.setText(Double.toString(adeudo));
        etMultaEnRecibo.setText(cuenta.get(3));
        jpRecibo.setVisible(true);
    }

}
